# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_capture_client.models.delivery_slot_dto import DeliverySlotDto

class TestDeliverySlotDto(unittest.TestCase):
    """DeliverySlotDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeliverySlotDto:
        """Test DeliverySlotDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeliverySlotDto`
        """
        model = DeliverySlotDto()
        if include_optional:
            return DeliverySlotDto(
                metadata = order_capture_client.models.delivery_slot_metadata_dto.DeliverySlotMetadataDto(
                    time_zone = 'Europe/Stockholm', 
                    has_price_deviation = True, ),
                id = '48d9e0fe-4acb-4ee0-a381-0fc2014d7f48',
                from_date_time = '2021-07-16T10:00:00.000',
                to_date_time = '2021-07-16T18:00:00.000',
                capability = AUTH_TO_LEAVE,
                price = order_capture_client.models.slot_price.SlotPrice(
                    incl_tax = 1.337, 
                    excl_tax = 1.337, )
            )
        else:
            return DeliverySlotDto(
        )
        """

    def testDeliverySlotDto(self):
        """Test DeliverySlotDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
