# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_capture_client.models.delivery_item_dto import DeliveryItemDto

class TestDeliveryItemDto(unittest.TestCase):
    """DeliveryItemDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeliveryItemDto:
        """Test DeliveryItemDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeliveryItemDto`
        """
        model = DeliveryItemDto()
        if include_optional:
            return DeliveryItemDto(
                item_no = '80386507',
                item_type = '',
                quantity = 1.337,
                ship_node = 'CDC.203',
                parent_id = '39256066'
            )
        else:
            return DeliveryItemDto(
        )
        """

    def testDeliveryItemDto(self):
        """Test DeliveryItemDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
