# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_capture_client.api.checkout_deliver_services_delivery_time_windows_service_time_windows_api import CheckoutDeliverServicesDeliveryTimeWindowsServiceTimeWindowsApi


class TestCheckoutDeliverServicesDeliveryTimeWindowsServiceTimeWindowsApi(unittest.TestCase):
    """CheckoutDeliverServicesDeliveryTimeWindowsServiceTimeWindowsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CheckoutDeliverServicesDeliveryTimeWindowsServiceTimeWindowsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_selected_delivery_and_service(self) -> None:
        """Test case for delete_selected_delivery_and_service

        Service to remove the choices the consumer saved earlier
        """
        pass

    def test_get_collect_delivery_services(self) -> None:
        """Test case for get_collect_delivery_services

        Service for Customer to get all available Collect Delivery Services
        """
        pass

    def test_get_delivery_time_windows(self) -> None:
        """Test case for get_delivery_time_windows

        Service for Customer to select choice of the delivery service and its time windows and also time windows for a selected service such as assembly, installation etc.
        """
        pass

    def test_get_home_delivery_services(self) -> None:
        """Test case for get_home_delivery_services

        Service for Customer to get all available Home Delivery Services
        """
        pass

    def test_get_saved_selected_deliver_and_service(self) -> None:
        """Test case for get_saved_selected_deliver_and_service

        Service for Customer to change choice of the delivery service and its time windows and also time windows for a selected service such as assembly, installation etc.
        """
        pass

    def test_get_service_time_windows(self) -> None:
        """Test case for get_service_time_windows

        Service for Customer to get the calendar time windows for a selected delivery service
        """
        pass

    def test_save_selected_delivery_and_service(self) -> None:
        """Test case for save_selected_delivery_and_service

        Service for Customer to select choice of the delivery service and its time windows and also time windows for a selected service such as assembly, installation etc.
        """
        pass


if __name__ == '__main__':
    unittest.main()
