# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_capture_client.models.spe_coupon import SpeCoupon

class TestSpeCoupon(unittest.TestCase):
    """SpeCoupon unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpeCoupon:
        """Test SpeCoupon
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SpeCoupon`
        """
        model = SpeCoupon()
        if include_optional:
            return SpeCoupon(
                discount_code = '',
                discount_amount = [
                    order_capture_client.models.spe_amount.SpeAmount(
                        view_type = '', 
                        amount = 1.337, )
                    ],
                info_messages = [
                    order_capture_client.models.spe_info_message.SpeInfoMessage(
                        view_type = '', 
                        message_id = '', 
                        message_text = '', )
                    ],
                texts = [
                    order_capture_client.models.spe_coupon_text.SpeCouponText(
                        lang_code = '', 
                        name = '', )
                    ],
                valid_customer_types = [
                    ''
                    ],
                service_discount = True
            )
        else:
            return SpeCoupon(
        )
        """

    def testSpeCoupon(self):
        """Test SpeCoupon"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
