# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_capture_client.models.price_excl_savings import PriceExclSavings

class TestPriceExclSavings(unittest.TestCase):
    """PriceExclSavings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PriceExclSavings:
        """Test PriceExclSavings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PriceExclSavings`
        """
        model = PriceExclSavings()
        if include_optional:
            return PriceExclSavings(
                incl_tax = 1.337,
                excl_tax = 1.337,
                tax = 1.337,
                tax_list = [
                    order_capture_client.models.tax.Tax(
                        tax_jurisdiction = order_capture_client.models.tax_jurisdiction.TaxJurisdiction(
                            tax_jurisdiction_type = '', 
                            tax_jurisdiction_code = '', ), 
                        type = '', 
                        code = '', 
                        tax_percentage = 1.337, 
                        tax_amount = 1.337, 
                        taxable_amount = 1.337, )
                    ],
                tax_summary_list = [
                    order_capture_client.models.spe_tax_summary.SpeTaxSummary(
                        tax_type = '', 
                        total_tax_amount = 1.337, 
                        tax_percent = 1.337, )
                    ]
            )
        else:
            return PriceExclSavings(
        )
        """

    def testPriceExclSavings(self):
        """Test PriceExclSavings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
