# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_capture_client.models.service_item_request import ServiceItemRequest

class TestServiceItemRequest(unittest.TestCase):
    """ServiceItemRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceItemRequest:
        """Test ServiceItemRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceItemRequest`
        """
        model = ServiceItemRequest()
        if include_optional:
            return ServiceItemRequest(
                service_item_no = '',
                service_product_id = '',
                provider = '',
                pay_to_provider = True,
                item_reference_list = [
                    order_capture_client.models.item_reference_request.ItemReferenceRequest(
                        item_no = '', 
                        quantity = '', 
                        is_co_worker_assistance_needed = True, )
                    ],
                exceptional_scenario = order_capture_client.models.exceptional_scenario.ExceptionalScenario(
                    exception_code = '', 
                    exception_reason = '', )
            )
        else:
            return ServiceItemRequest(
                item_reference_list = [
                    order_capture_client.models.item_reference_request.ItemReferenceRequest(
                        item_no = '', 
                        quantity = '', 
                        is_co_worker_assistance_needed = True, )
                    ],
        )
        """

    def testServiceItemRequest(self):
        """Test ServiceItemRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
