# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_capture_client.models.service_area_dto import ServiceAreaDto

class TestServiceAreaDto(unittest.TestCase):
    """ServiceAreaDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceAreaDto:
        """Test ServiceAreaDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceAreaDto`
        """
        model = ServiceAreaDto()
        if include_optional:
            return ServiceAreaDto(
                zip_code = 'H1E2V4',
                state_code = 'QC',
                city = '',
                delivery_country_code = 'LU'
            )
        else:
            return ServiceAreaDto(
                zip_code = 'H1E2V4',
        )
        """

    def testServiceAreaDto(self):
        """Test ServiceAreaDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
