# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_capture_client.models.tax_jurisdiction import TaxJurisdiction

class TestTaxJurisdiction(unittest.TestCase):
    """TaxJurisdiction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaxJurisdiction:
        """Test TaxJurisdiction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaxJurisdiction`
        """
        model = TaxJurisdiction()
        if include_optional:
            return TaxJurisdiction(
                tax_jurisdiction_type = '',
                tax_jurisdiction_code = ''
            )
        else:
            return TaxJurisdiction(
        )
        """

    def testTaxJurisdiction(self):
        """Test TaxJurisdiction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
