# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_capture_client.models.delivery_time_windows_of_target_hd_dto import DeliveryTimeWindowsOfTargetHDDto

class TestDeliveryTimeWindowsOfTargetHDDto(unittest.TestCase):
    """DeliveryTimeWindowsOfTargetHDDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeliveryTimeWindowsOfTargetHDDto:
        """Test DeliveryTimeWindowsOfTargetHDDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeliveryTimeWindowsOfTargetHDDto`
        """
        model = DeliveryTimeWindowsOfTargetHDDto()
        if include_optional:
            return DeliveryTimeWindowsOfTargetHDDto(
                slots = [
                    order_capture_client.models.delivery_slot_of_target_hd_dto.DeliverySlotOfTargetHDDto(
                        id = '48d9e0fe-4acb-4ee0-a381-0fc2014d7f48', 
                        from_date_time = '2021-07-16T10:00:00.000', 
                        to_date_time = '2021-07-16T18:00:00.000', 
                        price = order_capture_client.models.delta_price_dto.DeltaPriceDto(
                            incl_tax = 1.337, 
                            excl_tax = 1.337, 
                            delta_price = 1.337, ), )
                    ],
                earliest_possible_slot = order_capture_client.models.delivery_slot_of_target_hd_dto.DeliverySlotOfTargetHDDto(
                    id = '48d9e0fe-4acb-4ee0-a381-0fc2014d7f48', 
                    from_date_time = '2021-07-16T10:00:00.000', 
                    to_date_time = '2021-07-16T18:00:00.000', 
                    price = order_capture_client.models.delta_price_dto.DeltaPriceDto(
                        incl_tax = 1.337, 
                        excl_tax = 1.337, 
                        delta_price = 1.337, ), )
            )
        else:
            return DeliveryTimeWindowsOfTargetHDDto(
        )
        """

    def testDeliveryTimeWindowsOfTargetHDDto(self):
        """Test DeliveryTimeWindowsOfTargetHDDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
