# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_capture_client.api.checkout_questionnaires_api import CheckoutQuestionnairesApi


class TestCheckoutQuestionnairesApi(unittest.TestCase):
    """CheckoutQuestionnairesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CheckoutQuestionnairesApi()

    def tearDown(self) -> None:
        pass

    def test_get_questionnaires(self) -> None:
        """Test case for get_questionnaires

        Service for getting delivery & service questionnaires
        """
        pass

    def test_patch_questionnaire_answers(self) -> None:
        """Test case for patch_questionnaire_answers

        Service to save the answered delivery & service questions
        """
        pass


if __name__ == '__main__':
    unittest.main()
