# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_capture_client.models.unavailable_item_dto import UnavailableItemDto

class TestUnavailableItemDto(unittest.TestCase):
    """UnavailableItemDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnavailableItemDto:
        """Test UnavailableItemDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnavailableItemDto`
        """
        model = UnavailableItemDto()
        if include_optional:
            return UnavailableItemDto(
                id = '090aae12-9a55-4080-8920-e3450f6cb881',
                line_id = '1',
                item_no = '80386507',
                type = 'SPR',
                required_quantity = 5,
                available_quantity = 3,
                unavailable_reason = 'OP_NOT_ENOUGH_PROD_CHOICES',
                unavailable_reason_code_map = {
                    'key' : ''
                    }
            )
        else:
            return UnavailableItemDto(
        )
        """

    def testUnavailableItemDto(self):
        """Test UnavailableItemDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
