# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_capture_client.models.delivery_time_window_metadata_dto import DeliveryTimeWindowMetadataDto

class TestDeliveryTimeWindowMetadataDto(unittest.TestCase):
    """DeliveryTimeWindowMetadataDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeliveryTimeWindowMetadataDto:
        """Test DeliveryTimeWindowMetadataDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeliveryTimeWindowMetadataDto`
        """
        model = DeliveryTimeWindowMetadataDto()
        if include_optional:
            return DeliveryTimeWindowMetadataDto(
                has_capacity = True,
                cheapest_slot_id = '971ff3f1-c378-4611-8ff3-74b1c844015b'
            )
        else:
            return DeliveryTimeWindowMetadataDto(
        )
        """

    def testDeliveryTimeWindowMetadataDto(self):
        """Test DeliveryTimeWindowMetadataDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
