# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_capture_client.models.tw_config_dto import TWConfigDto

class TestTWConfigDto(unittest.TestCase):
    """TWConfigDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TWConfigDto:
        """Test TWConfigDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TWConfigDto`
        """
        model = TWConfigDto()
        if include_optional:
            return TWConfigDto(
                search_number_of_days = '',
                excl_tax_country = True
            )
        else:
            return TWConfigDto(
        )
        """

    def testTWConfigDto(self):
        """Test TWConfigDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
