# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_capture_client.models.possible_delivery_time_windows_dto import PossibleDeliveryTimeWindowsDto

class TestPossibleDeliveryTimeWindowsDto(unittest.TestCase):
    """PossibleDeliveryTimeWindowsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PossibleDeliveryTimeWindowsDto:
        """Test PossibleDeliveryTimeWindowsDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PossibleDeliveryTimeWindowsDto`
        """
        model = PossibleDeliveryTimeWindowsDto()
        if include_optional:
            return PossibleDeliveryTimeWindowsDto(
                metadata = order_capture_client.models.delivery_time_windows_metadata_dto.DeliveryTimeWindowsMetadataDto(
                    max_slot_price = 1.337, 
                    min_slot_price = 1.337, ),
                time_windows = [
                    order_capture_client.models.possible_delivery_time_window_dto.PossibleDeliveryTimeWindowDto(
                        metadata = order_capture_client.models.delivery_time_window_metadata_dto.DeliveryTimeWindowMetadataDto(
                            has_capacity = True, 
                            cheapest_slot_id = '971ff3f1-c378-4611-8ff3-74b1c844015b', ), 
                        error = order_capture_client.models.error.Error(
                            type = 'INTEGRATION_APP_ERROR', 
                            service = 'DELIVERY_ARRANGEMENTS', 
                            solution_id = '', 
                            pick_up_point_data = [
                                ''
                                ], 
                            error_detail = order_capture_client.models.error_detail.ErrorDetail(
                                error_code = '', 
                                error_description = '', 
                                error_unique_exception_id = '', ), ), 
                        delivery_id = 'cc162740-be53-4b61-9277-a51ef7cd8928', 
                        fulfillment_delivery_id = 'iSOM provided delivery identifier', 
                        delivery_service_item_number = 'SGR50000875', 
                        pick_up_point_identifier = 'STO CP 094@IKEASTORE_DK', 
                        oc_pupid = '971ff3f1-c378-4611-8ff3-74b1c844015b', 
                        delivery_time_windows = It describes earliest and alternate slots that are applicable, )
                    ]
            )
        else:
            return PossibleDeliveryTimeWindowsDto(
        )
        """

    def testPossibleDeliveryTimeWindowsDto(self):
        """Test PossibleDeliveryTimeWindowsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
