# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_capture_client.models.coupon_info import CouponInfo

class TestCouponInfo(unittest.TestCase):
    """CouponInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CouponInfo:
        """Test CouponInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CouponInfo`
        """
        model = CouponInfo()
        if include_optional:
            return CouponInfo(
                discount_code = '',
                discount_amount = 1.337,
                roll_up_price_type = 'FAMILY',
                text = '',
                coupon_metadata = order_capture_client.models.coupon_metadata.CouponMetadata(
                    is_coupon_valid = True, 
                    reason_of_failure = 'INVALID_COUPON', 
                    valid_customer_types = [
                        'PRIVATE'
                        ], )
            )
        else:
            return CouponInfo(
        )
        """

    def testCouponInfo(self):
        """Test CouponInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
