# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_capture_client.models.tw_config import TWConfig

class TestTWConfig(unittest.TestCase):
    """TWConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TWConfig:
        """Test TWConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TWConfig`
        """
        model = TWConfig()
        if include_optional:
            return TWConfig(
                search_number_of_days = '',
                excl_tax_country = True,
                enable_isom_with_kong_gw = True,
                enable_service_price_with_kong_gw = True
            )
        else:
            return TWConfig(
        )
        """

    def testTWConfig(self):
        """Test TWConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
