# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from order_capture_client.models.removal_service_item_request import RemovalServiceItemRequest

class TestRemovalServiceItemRequest(unittest.TestCase):
    """RemovalServiceItemRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RemovalServiceItemRequest:
        """Test RemovalServiceItemRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RemovalServiceItemRequest`
        """
        model = RemovalServiceItemRequest()
        if include_optional:
            return RemovalServiceItemRequest(
                service_item_no = '',
                service_product_id = '',
                provider = '',
                pay_to_provider = True,
                quantity = ''
            )
        else:
            return RemovalServiceItemRequest(
        )
        """

    def testRemovalServiceItemRequest(self):
        """Test RemovalServiceItemRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
