# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from order_capture_client.models.delivery_slot_of_target_hd_dto import DeliverySlotOfTargetHDDto
from typing import Optional, Set
from typing_extensions import Self

class DeliveryTimeWindowsOfTargetHDDto(BaseModel):
    """
    It represents the target delivery timewindow details for which we need to calculate the delta prices for
    """ # noqa: E501
    slots: Optional[List[DeliverySlotOfTargetHDDto]] = Field(default=None, description="It represents the list of alternative slots of the target delivery with calculated delta price values")
    earliest_possible_slot: Optional[DeliverySlotOfTargetHDDto] = Field(default=None, alias="earliestPossibleSlot")
    __properties: ClassVar[List[str]] = ["slots", "earliestPossibleSlot"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeliveryTimeWindowsOfTargetHDDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in slots (list)
        _items = []
        if self.slots:
            for _item_slots in self.slots:
                if _item_slots:
                    _items.append(_item_slots.to_dict())
            _dict['slots'] = _items
        # override the default output from pydantic by calling `to_dict()` of earliest_possible_slot
        if self.earliest_possible_slot:
            _dict['earliestPossibleSlot'] = self.earliest_possible_slot.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeliveryTimeWindowsOfTargetHDDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "slots": [DeliverySlotOfTargetHDDto.from_dict(_item) for _item in obj["slots"]] if obj.get("slots") is not None else None,
            "earliestPossibleSlot": DeliverySlotOfTargetHDDto.from_dict(obj["earliestPossibleSlot"]) if obj.get("earliestPossibleSlot") is not None else None
        })
        return _obj


