# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from order_capture_client.models.pick_up_point_dto import PickUpPointDto
from order_capture_client.models.possible_pick_up_point_metadata_dto import PossiblePickUpPointMetadataDto
from typing import Optional, Set
from typing_extensions import Self

class PossiblePickUpPointsDto(BaseModel):
    """
    This node is available only if the delivery service fulfillment type is COLLECT. This node wraps the pickup point metadata along with list of pick up points for a delivery
    """ # noqa: E501
    possible_pick_up_point_metadata: Optional[PossiblePickUpPointMetadataDto] = Field(default=None, alias="possiblePickUpPointMetadata")
    pick_up_points: Optional[List[PickUpPointDto]] = Field(default=None, description="List of possible pick up points with details", alias="pickUpPoints")
    __properties: ClassVar[List[str]] = ["possiblePickUpPointMetadata", "pickUpPoints"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PossiblePickUpPointsDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of possible_pick_up_point_metadata
        if self.possible_pick_up_point_metadata:
            _dict['possiblePickUpPointMetadata'] = self.possible_pick_up_point_metadata.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in pick_up_points (list)
        _items = []
        if self.pick_up_points:
            for _item_pick_up_points in self.pick_up_points:
                if _item_pick_up_points:
                    _items.append(_item_pick_up_points.to_dict())
            _dict['pickUpPoints'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PossiblePickUpPointsDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "possiblePickUpPointMetadata": PossiblePickUpPointMetadataDto.from_dict(obj["possiblePickUpPointMetadata"]) if obj.get("possiblePickUpPointMetadata") is not None else None,
            "pickUpPoints": [PickUpPointDto.from_dict(_item) for _item in obj["pickUpPoints"]] if obj.get("pickUpPoints") is not None else None
        })
        return _obj


