# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from order_capture_client.models.selected_delivery_and_time_windows_dto import SelectedDeliveryAndTimeWindowsDto
from typing import Optional, Set
from typing_extensions import Self

class SelectedDeliveryServiceDto(BaseModel):
    """
    It describes the selected delivery service and its related information such as delivery, time window, pick up point etc
    """ # noqa: E501
    delivery_service_id: StrictStr = Field(description="It refers to the selected delivery service ID", alias="deliveryServiceId")
    delivery_and_time_windows: List[SelectedDeliveryAndTimeWindowsDto] = Field(description="It refers to details related to selected time window and pick up point if it is collect", alias="deliveryAndTimeWindows")
    __properties: ClassVar[List[str]] = ["deliveryServiceId", "deliveryAndTimeWindows"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SelectedDeliveryServiceDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in delivery_and_time_windows (list)
        _items = []
        if self.delivery_and_time_windows:
            for _item_delivery_and_time_windows in self.delivery_and_time_windows:
                if _item_delivery_and_time_windows:
                    _items.append(_item_delivery_and_time_windows.to_dict())
            _dict['deliveryAndTimeWindows'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SelectedDeliveryServiceDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "deliveryServiceId": obj.get("deliveryServiceId"),
            "deliveryAndTimeWindows": [SelectedDeliveryAndTimeWindowsDto.from_dict(_item) for _item in obj["deliveryAndTimeWindows"]] if obj.get("deliveryAndTimeWindows") is not None else None
        })
        return _obj


