# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ServiceArea(BaseModel):
    """
    ServiceArea
    """ # noqa: E501
    zip_code: Optional[StrictStr] = Field(default=None, description="It refers to the customer service location for delivery or a service. Please note that OC will pass this zip code as-is for delivery calculation and no formatting will be applied", alias="zipCode")
    state_code: Optional[StrictStr] = Field(default=None, description="It refers to state code and it should be a 2 character state code. It is mandatory for US, CA, AU", alias="stateCode")
    city: Optional[StrictStr] = Field(default=None, description="It refers to state code and it should be a 2 character state code. It is mandatory for US, CA, AU")
    id: Optional[StrictStr] = Field(default=None, description="OC generated UUID for the service area")
    delivery_country_code: Optional[StrictStr] = Field(default=None, description="This is used in case of delivery to another country in special case i.e. Luxembourg", alias="deliveryCountryCode")
    __properties: ClassVar[List[str]] = ["zipCode", "stateCode", "city", "id", "deliveryCountryCode"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServiceArea from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServiceArea from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "zipCode": obj.get("zipCode"),
            "stateCode": obj.get("stateCode"),
            "city": obj.get("city"),
            "id": obj.get("id"),
            "deliveryCountryCode": obj.get("deliveryCountryCode")
        })
        return _obj


