# coding: utf-8

"""
    Sales Item API

    Get information for items in different contexts. Note that this is an extendable interface that might introduce new types without increase in major version including new values in enumerations. 

    The version of the OpenAPI document: 1.45.0
    Contact: paul.eriksson@ingka.ikea.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from salesitem_client.models.estimated_time import EstimatedTime
from salesitem_client.models.required_tool import RequiredTool
from typing import Optional, Set
from typing_extensions import Self

class AssemblyEffort(BaseModel):
    """
    AssemblyEffort
    """ # noqa: E501
    estimated_time: Optional[EstimatedTime] = Field(default=None, alias="estimatedTime")
    required_persons: Optional[StrictInt] = Field(default=None, alias="requiredPersons")
    required_tools: Optional[List[RequiredTool]] = Field(default=None, alias="requiredTools")
    type: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["estimatedTime", "requiredPersons", "requiredTools", "type"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['CUSTOMER_ASSEMBLY']):
            raise ValueError("must be one of enum values ('CUSTOMER_ASSEMBLY')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AssemblyEffort from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of estimated_time
        if self.estimated_time:
            _dict['estimatedTime'] = self.estimated_time.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in required_tools (list)
        _items = []
        if self.required_tools:
            for _item_required_tools in self.required_tools:
                if _item_required_tools:
                    _items.append(_item_required_tools.to_dict())
            _dict['requiredTools'] = _items
        # set to None if required_persons (nullable) is None
        # and model_fields_set contains the field
        if self.required_persons is None and "required_persons" in self.model_fields_set:
            _dict['requiredPersons'] = None

        # set to None if required_tools (nullable) is None
        # and model_fields_set contains the field
        if self.required_tools is None and "required_tools" in self.model_fields_set:
            _dict['requiredTools'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AssemblyEffort from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "estimatedTime": EstimatedTime.from_dict(obj["estimatedTime"]) if obj.get("estimatedTime") is not None else None,
            "requiredPersons": obj.get("requiredPersons"),
            "requiredTools": [RequiredTool.from_dict(_item) for _item in obj["requiredTools"]] if obj.get("requiredTools") is not None else None,
            "type": obj.get("type")
        })
        return _obj


