# coding: utf-8

"""
    Sales Item API

    Get information for items in different contexts. Note that this is an extendable interface that might introduce new types without increase in major version including new values in enumerations. 

    The version of the OpenAPI document: 1.45.0
    Contact: paul.eriksson@ingka.ikea.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from salesitem_client.models.compliance_information_section import ComplianceInformationSection
from typing import Optional, Set
from typing_extensions import Self

class ComplianceInformation(BaseModel):
    """
    ComplianceInformation
    """ # noqa: E501
    sections: List[ComplianceInformationSection]
    type: StrictStr
    __properties: ClassVar[List[str]] = ["sections", "type"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['CALIFORNIA_AB_1200', 'COUNTRY_OF_ORIGIN', 'ENERGY_DECLARATION', 'GENERAL_CUSTOMER_INFO', 'INDIA_COUNTRY_OF_ORIGIN', 'LAW_LABEL', 'SOLID_WOOD_DECLARATION', 'TIP_OVER_HAZARD']):
            raise ValueError("must be one of enum values ('CALIFORNIA_AB_1200', 'COUNTRY_OF_ORIGIN', 'ENERGY_DECLARATION', 'GENERAL_CUSTOMER_INFO', 'INDIA_COUNTRY_OF_ORIGIN', 'LAW_LABEL', 'SOLID_WOOD_DECLARATION', 'TIP_OVER_HAZARD')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ComplianceInformation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in sections (list)
        _items = []
        if self.sections:
            for _item_sections in self.sections:
                if _item_sections:
                    _items.append(_item_sections.to_dict())
            _dict['sections'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ComplianceInformation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sections": [ComplianceInformationSection.from_dict(_item) for _item in obj["sections"]] if obj.get("sections") is not None else None,
            "type": obj.get("type")
        })
        return _obj


