# coding: utf-8

"""
    Sales Item API

    Get information for items in different contexts. Note that this is an extendable interface that might introduce new types without increase in major version including new values in enumerations. 

    The version of the OpenAPI document: 1.45.0
    Contact: paul.eriksson@ingka.ikea.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from salesitem_client.models.service_price_previous_sales_price import ServicePricePreviousSalesPrice
from typing import Optional, Set
from typing_extensions import Self

class ServicePrice(BaseModel):
    """
    ServicePrice
    """ # noqa: E501
    change_reason: Optional[StrictStr] = Field(default=None, description="Further information about the specific price.", alias="changeReason")
    currency_code: Optional[Annotated[str, Field(strict=True, max_length=3)]] = Field(default=None, description="Currency code for the price values", alias="currencyCode")
    indicative_total_tax: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="indicativeTotalTax")
    previous_sales_price: Optional[ServicePricePreviousSalesPrice] = Field(default=None, alias="previousSalesPrice")
    price_excl_tax: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="priceExclTax")
    price_incl_tax: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="priceInclTax")
    service_product_id: Optional[StrictStr] = Field(default=None, description="The id of the service product as defined by the retailer (e.g. BASIC_KITCHEN_INSTALL).", alias="serviceProductId")
    type: Optional[Annotated[str, Field(strict=True, max_length=50)]] = None
    valid_from_date: Optional[date] = Field(default=None, alias="validFromDate")
    valid_to_date: Optional[date] = Field(default=None, alias="validToDate")
    __properties: ClassVar[List[str]] = ["changeReason", "currencyCode", "indicativeTotalTax", "previousSalesPrice", "priceExclTax", "priceInclTax", "serviceProductId", "type", "validFromDate", "validToDate"]

    @field_validator('change_reason')
    def change_reason_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NewLowerPrice', 'TimeRestrictedOffer']):
            raise ValueError("must be one of enum values ('NewLowerPrice', 'TimeRestrictedOffer')")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['RegularSalesUnitPrice', 'IKEAFamilySalesUnitPrice']):
            raise ValueError("must be one of enum values ('RegularSalesUnitPrice', 'IKEAFamilySalesUnitPrice')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServicePrice from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of previous_sales_price
        if self.previous_sales_price:
            _dict['previousSalesPrice'] = self.previous_sales_price.to_dict()
        # set to None if indicative_total_tax (nullable) is None
        # and model_fields_set contains the field
        if self.indicative_total_tax is None and "indicative_total_tax" in self.model_fields_set:
            _dict['indicativeTotalTax'] = None

        # set to None if previous_sales_price (nullable) is None
        # and model_fields_set contains the field
        if self.previous_sales_price is None and "previous_sales_price" in self.model_fields_set:
            _dict['previousSalesPrice'] = None

        # set to None if service_product_id (nullable) is None
        # and model_fields_set contains the field
        if self.service_product_id is None and "service_product_id" in self.model_fields_set:
            _dict['serviceProductId'] = None

        # set to None if valid_from_date (nullable) is None
        # and model_fields_set contains the field
        if self.valid_from_date is None and "valid_from_date" in self.model_fields_set:
            _dict['validFromDate'] = None

        # set to None if valid_to_date (nullable) is None
        # and model_fields_set contains the field
        if self.valid_to_date is None and "valid_to_date" in self.model_fields_set:
            _dict['validToDate'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServicePrice from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "changeReason": obj.get("changeReason"),
            "currencyCode": obj.get("currencyCode"),
            "indicativeTotalTax": obj.get("indicativeTotalTax"),
            "previousSalesPrice": ServicePricePreviousSalesPrice.from_dict(obj["previousSalesPrice"]) if obj.get("previousSalesPrice") is not None else None,
            "priceExclTax": obj.get("priceExclTax"),
            "priceInclTax": obj.get("priceInclTax"),
            "serviceProductId": obj.get("serviceProductId"),
            "type": obj.get("type"),
            "validFromDate": obj.get("validFromDate"),
            "validToDate": obj.get("validToDate")
        })
        return _obj


