# coding: utf-8

"""
    Sales Item API

    Get information for items in different contexts. Note that this is an extendable interface that might introduce new types without increase in major version including new values in enumerations. 

    The version of the OpenAPI document: 1.45.0
    Contact: paul.eriksson@ingka.ikea.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TechnicalInformationPart(BaseModel):
    """
    TechnicalInformationPart
    """ # noqa: E501
    explanatory_text: Optional[StrictStr] = Field(default=None, alias="explanatoryText")
    legal: StrictBool
    range_no: StrictStr = Field(alias="rangeNo")
    range_text: Optional[StrictStr] = Field(default=None, alias="rangeText")
    text: StrictStr
    text_imperial: Optional[StrictStr] = Field(default=None, alias="textImperial")
    text_metric: Optional[StrictStr] = Field(default=None, alias="textMetric")
    text_no: StrictStr = Field(alias="textNo")
    unit_imperial: Optional[StrictStr] = Field(default=None, alias="unitImperial")
    unit_metric: Optional[StrictStr] = Field(default=None, alias="unitMetric")
    value_imperial: Optional[StrictStr] = Field(default=None, alias="valueImperial")
    value_metric: Optional[StrictStr] = Field(default=None, alias="valueMetric")
    __properties: ClassVar[List[str]] = ["explanatoryText", "legal", "rangeNo", "rangeText", "text", "textImperial", "textMetric", "textNo", "unitImperial", "unitMetric", "valueImperial", "valueMetric"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TechnicalInformationPart from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TechnicalInformationPart from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "explanatoryText": obj.get("explanatoryText"),
            "legal": obj.get("legal"),
            "rangeNo": obj.get("rangeNo"),
            "rangeText": obj.get("rangeText"),
            "text": obj.get("text"),
            "textImperial": obj.get("textImperial"),
            "textMetric": obj.get("textMetric"),
            "textNo": obj.get("textNo"),
            "unitImperial": obj.get("unitImperial"),
            "unitMetric": obj.get("unitMetric"),
            "valueImperial": obj.get("valueImperial"),
            "valueMetric": obj.get("valueMetric")
        })
        return _obj


