# coding: utf-8

"""
    Sales Item API

    Get information for items in different contexts. Note that this is an extendable interface that might introduce new types without increase in major version including new values in enumerations. 

    The version of the OpenAPI document: 1.45.0
    Contact: paul.eriksson@ingka.ikea.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictStr, field_validator
from typing import Optional
from typing_extensions import Annotated
from salesitem_client.models.availability_classification_response import AvailabilityClassificationResponse

from salesitem_client.api_client import ApiClient, RequestSerialized
from salesitem_client.api_response import ApiResponse
from salesitem_client.rest import RESTResponseType


class AvailabilityClassificationApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_item_availability_classifications(
        self,
        class_unit_type: Annotated[StrictStr, Field(description="`classUnitType` must be Retail Unit (`ru`). It is used together with `classUnitCode` to give context when invoking AvailabilityClassifications API.  Retail Unit must be combined with a valid `classUnitCode`. For example, `SE` for Sweden or `DE` for Germany.  A list of valid Retail Units can be found [in CBD](https://iwww.cbdview.ikea.com/) (requires VPN or internal network). ")],
        class_unit_code: Annotated[str, Field(min_length=2, strict=True, max_length=5, description="`classUnitCode` is the unique identifier of a Class Unit when combined with a `classUnitType`.  A valid `classUnitCode` always has a pattern like `^([A-Z]|[0-9]){2,5}$`. Note that the Selling Range APIs are case insensitive when it comes to the `classUnitCode` path parameter and lower case is always internally converted to upper case.  A list of valid Class Units can be found [in CBD](https://iwww.cbdview.ikea.com/) (requires VPN or internal network). ")],
        channel: Annotated[Optional[StrictStr], Field(description="Optional filter to find a rule for a specific channel. If not passed all channels are returned. ALL indicates channel independent.")] = None,
        type: Annotated[Optional[StrictStr], Field(description="Optional filter to find a specific classification type. If not passed all types are returned. CASH_AND_CARRY and HOME_DELIVERY types have been decommissioned from the API response and moved to the CIA API.")] = None,
        item_nos: Annotated[Optional[Annotated[str, Field(min_length=0, strict=True, max_length=799)]], Field(description="One or many item numbers (maximum 50). If more than one - separated by commas")] = None,
        value: Annotated[Optional[StrictBool], Field(description="Optional filter to find a specific classification value, true or false. If not passed all values are returned.")] = None,
        item_type: Annotated[Optional[StrictStr], Field(description="Optional filter to find a specific item type. If not passed all types are returned.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> AvailabilityClassificationResponse:
        """Get availability classification information (operational range) of the choosen class unit. Used to get a complete list of items based on at least one classification type. Please note that you have to specify either the `itemNos` query parameter or the `type` query parameter.

        Get the current list of itemsAvailabilityClassifications

        :param class_unit_type: `classUnitType` must be Retail Unit (`ru`). It is used together with `classUnitCode` to give context when invoking AvailabilityClassifications API.  Retail Unit must be combined with a valid `classUnitCode`. For example, `SE` for Sweden or `DE` for Germany.  A list of valid Retail Units can be found [in CBD](https://iwww.cbdview.ikea.com/) (requires VPN or internal network).  (required)
        :type class_unit_type: str
        :param class_unit_code: `classUnitCode` is the unique identifier of a Class Unit when combined with a `classUnitType`.  A valid `classUnitCode` always has a pattern like `^([A-Z]|[0-9]){2,5}$`. Note that the Selling Range APIs are case insensitive when it comes to the `classUnitCode` path parameter and lower case is always internally converted to upper case.  A list of valid Class Units can be found [in CBD](https://iwww.cbdview.ikea.com/) (requires VPN or internal network).  (required)
        :type class_unit_code: str
        :param channel: Optional filter to find a rule for a specific channel. If not passed all channels are returned. ALL indicates channel independent.
        :type channel: str
        :param type: Optional filter to find a specific classification type. If not passed all types are returned. CASH_AND_CARRY and HOME_DELIVERY types have been decommissioned from the API response and moved to the CIA API.
        :type type: str
        :param item_nos: One or many item numbers (maximum 50). If more than one - separated by commas
        :type item_nos: str
        :param value: Optional filter to find a specific classification value, true or false. If not passed all values are returned.
        :type value: bool
        :param item_type: Optional filter to find a specific item type. If not passed all types are returned.
        :type item_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_item_availability_classifications_serialize(
            class_unit_type=class_unit_type,
            class_unit_code=class_unit_code,
            channel=channel,
            type=type,
            item_nos=item_nos,
            value=value,
            item_type=item_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AvailabilityClassificationResponse",
            '400': "AvailabilityClassificationResponse",
            '401': "AvailabilityClassificationResponse",
            '403': "AvailabilityClassificationResponse",
            '429': "AvailabilityClassificationResponse",
            '500': "AvailabilityClassificationResponse",
            '503': "AvailabilityClassificationResponse",
            '504': "AvailabilityClassificationResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_item_availability_classifications_with_http_info(
        self,
        class_unit_type: Annotated[StrictStr, Field(description="`classUnitType` must be Retail Unit (`ru`). It is used together with `classUnitCode` to give context when invoking AvailabilityClassifications API.  Retail Unit must be combined with a valid `classUnitCode`. For example, `SE` for Sweden or `DE` for Germany.  A list of valid Retail Units can be found [in CBD](https://iwww.cbdview.ikea.com/) (requires VPN or internal network). ")],
        class_unit_code: Annotated[str, Field(min_length=2, strict=True, max_length=5, description="`classUnitCode` is the unique identifier of a Class Unit when combined with a `classUnitType`.  A valid `classUnitCode` always has a pattern like `^([A-Z]|[0-9]){2,5}$`. Note that the Selling Range APIs are case insensitive when it comes to the `classUnitCode` path parameter and lower case is always internally converted to upper case.  A list of valid Class Units can be found [in CBD](https://iwww.cbdview.ikea.com/) (requires VPN or internal network). ")],
        channel: Annotated[Optional[StrictStr], Field(description="Optional filter to find a rule for a specific channel. If not passed all channels are returned. ALL indicates channel independent.")] = None,
        type: Annotated[Optional[StrictStr], Field(description="Optional filter to find a specific classification type. If not passed all types are returned. CASH_AND_CARRY and HOME_DELIVERY types have been decommissioned from the API response and moved to the CIA API.")] = None,
        item_nos: Annotated[Optional[Annotated[str, Field(min_length=0, strict=True, max_length=799)]], Field(description="One or many item numbers (maximum 50). If more than one - separated by commas")] = None,
        value: Annotated[Optional[StrictBool], Field(description="Optional filter to find a specific classification value, true or false. If not passed all values are returned.")] = None,
        item_type: Annotated[Optional[StrictStr], Field(description="Optional filter to find a specific item type. If not passed all types are returned.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[AvailabilityClassificationResponse]:
        """Get availability classification information (operational range) of the choosen class unit. Used to get a complete list of items based on at least one classification type. Please note that you have to specify either the `itemNos` query parameter or the `type` query parameter.

        Get the current list of itemsAvailabilityClassifications

        :param class_unit_type: `classUnitType` must be Retail Unit (`ru`). It is used together with `classUnitCode` to give context when invoking AvailabilityClassifications API.  Retail Unit must be combined with a valid `classUnitCode`. For example, `SE` for Sweden or `DE` for Germany.  A list of valid Retail Units can be found [in CBD](https://iwww.cbdview.ikea.com/) (requires VPN or internal network).  (required)
        :type class_unit_type: str
        :param class_unit_code: `classUnitCode` is the unique identifier of a Class Unit when combined with a `classUnitType`.  A valid `classUnitCode` always has a pattern like `^([A-Z]|[0-9]){2,5}$`. Note that the Selling Range APIs are case insensitive when it comes to the `classUnitCode` path parameter and lower case is always internally converted to upper case.  A list of valid Class Units can be found [in CBD](https://iwww.cbdview.ikea.com/) (requires VPN or internal network).  (required)
        :type class_unit_code: str
        :param channel: Optional filter to find a rule for a specific channel. If not passed all channels are returned. ALL indicates channel independent.
        :type channel: str
        :param type: Optional filter to find a specific classification type. If not passed all types are returned. CASH_AND_CARRY and HOME_DELIVERY types have been decommissioned from the API response and moved to the CIA API.
        :type type: str
        :param item_nos: One or many item numbers (maximum 50). If more than one - separated by commas
        :type item_nos: str
        :param value: Optional filter to find a specific classification value, true or false. If not passed all values are returned.
        :type value: bool
        :param item_type: Optional filter to find a specific item type. If not passed all types are returned.
        :type item_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_item_availability_classifications_serialize(
            class_unit_type=class_unit_type,
            class_unit_code=class_unit_code,
            channel=channel,
            type=type,
            item_nos=item_nos,
            value=value,
            item_type=item_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AvailabilityClassificationResponse",
            '400': "AvailabilityClassificationResponse",
            '401': "AvailabilityClassificationResponse",
            '403': "AvailabilityClassificationResponse",
            '429': "AvailabilityClassificationResponse",
            '500': "AvailabilityClassificationResponse",
            '503': "AvailabilityClassificationResponse",
            '504': "AvailabilityClassificationResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_item_availability_classifications_without_preload_content(
        self,
        class_unit_type: Annotated[StrictStr, Field(description="`classUnitType` must be Retail Unit (`ru`). It is used together with `classUnitCode` to give context when invoking AvailabilityClassifications API.  Retail Unit must be combined with a valid `classUnitCode`. For example, `SE` for Sweden or `DE` for Germany.  A list of valid Retail Units can be found [in CBD](https://iwww.cbdview.ikea.com/) (requires VPN or internal network). ")],
        class_unit_code: Annotated[str, Field(min_length=2, strict=True, max_length=5, description="`classUnitCode` is the unique identifier of a Class Unit when combined with a `classUnitType`.  A valid `classUnitCode` always has a pattern like `^([A-Z]|[0-9]){2,5}$`. Note that the Selling Range APIs are case insensitive when it comes to the `classUnitCode` path parameter and lower case is always internally converted to upper case.  A list of valid Class Units can be found [in CBD](https://iwww.cbdview.ikea.com/) (requires VPN or internal network). ")],
        channel: Annotated[Optional[StrictStr], Field(description="Optional filter to find a rule for a specific channel. If not passed all channels are returned. ALL indicates channel independent.")] = None,
        type: Annotated[Optional[StrictStr], Field(description="Optional filter to find a specific classification type. If not passed all types are returned. CASH_AND_CARRY and HOME_DELIVERY types have been decommissioned from the API response and moved to the CIA API.")] = None,
        item_nos: Annotated[Optional[Annotated[str, Field(min_length=0, strict=True, max_length=799)]], Field(description="One or many item numbers (maximum 50). If more than one - separated by commas")] = None,
        value: Annotated[Optional[StrictBool], Field(description="Optional filter to find a specific classification value, true or false. If not passed all values are returned.")] = None,
        item_type: Annotated[Optional[StrictStr], Field(description="Optional filter to find a specific item type. If not passed all types are returned.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get availability classification information (operational range) of the choosen class unit. Used to get a complete list of items based on at least one classification type. Please note that you have to specify either the `itemNos` query parameter or the `type` query parameter.

        Get the current list of itemsAvailabilityClassifications

        :param class_unit_type: `classUnitType` must be Retail Unit (`ru`). It is used together with `classUnitCode` to give context when invoking AvailabilityClassifications API.  Retail Unit must be combined with a valid `classUnitCode`. For example, `SE` for Sweden or `DE` for Germany.  A list of valid Retail Units can be found [in CBD](https://iwww.cbdview.ikea.com/) (requires VPN or internal network).  (required)
        :type class_unit_type: str
        :param class_unit_code: `classUnitCode` is the unique identifier of a Class Unit when combined with a `classUnitType`.  A valid `classUnitCode` always has a pattern like `^([A-Z]|[0-9]){2,5}$`. Note that the Selling Range APIs are case insensitive when it comes to the `classUnitCode` path parameter and lower case is always internally converted to upper case.  A list of valid Class Units can be found [in CBD](https://iwww.cbdview.ikea.com/) (requires VPN or internal network).  (required)
        :type class_unit_code: str
        :param channel: Optional filter to find a rule for a specific channel. If not passed all channels are returned. ALL indicates channel independent.
        :type channel: str
        :param type: Optional filter to find a specific classification type. If not passed all types are returned. CASH_AND_CARRY and HOME_DELIVERY types have been decommissioned from the API response and moved to the CIA API.
        :type type: str
        :param item_nos: One or many item numbers (maximum 50). If more than one - separated by commas
        :type item_nos: str
        :param value: Optional filter to find a specific classification value, true or false. If not passed all values are returned.
        :type value: bool
        :param item_type: Optional filter to find a specific item type. If not passed all types are returned.
        :type item_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_item_availability_classifications_serialize(
            class_unit_type=class_unit_type,
            class_unit_code=class_unit_code,
            channel=channel,
            type=type,
            item_nos=item_nos,
            value=value,
            item_type=item_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "AvailabilityClassificationResponse",
            '400': "AvailabilityClassificationResponse",
            '401': "AvailabilityClassificationResponse",
            '403': "AvailabilityClassificationResponse",
            '429': "AvailabilityClassificationResponse",
            '500': "AvailabilityClassificationResponse",
            '503': "AvailabilityClassificationResponse",
            '504': "AvailabilityClassificationResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_item_availability_classifications_serialize(
        self,
        class_unit_type,
        class_unit_code,
        channel,
        type,
        item_nos,
        value,
        item_type,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if class_unit_type is not None:
            _path_params['classUnitType'] = class_unit_type
        if class_unit_code is not None:
            _path_params['classUnitCode'] = class_unit_code
        # process the query parameters
        if channel is not None:
            
            _query_params.append(('channel', channel))
            
        if type is not None:
            
            _query_params.append(('type', type))
            
        if item_nos is not None:
            
            _query_params.append(('itemNos', item_nos))
            
        if value is not None:
            
            _query_params.append(('value', value))
            
        if item_type is not None:
            
            _query_params.append(('itemType', item_type))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/vnd.ikea.api+json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'clientIDHeader'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/availabilityclassifications/{classUnitType}/{classUnitCode}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


