# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from order_capture_client.models.ga_error import GaError
from typing import Optional, Set
from typing_extensions import Self

class ErrorDetails(BaseModel):
    """
    ErrorDetails
    """ # noqa: E501
    type: Optional[StrictStr] = None
    title: Optional[StrictStr] = None
    timestamp: Optional[datetime] = None
    message: Optional[StrictStr] = None
    details: Optional[StrictStr] = None
    details_map: Optional[Dict[str, StrictStr]] = Field(default=None, alias="detailsMap")
    error_code: Optional[StrictInt] = Field(default=None, alias="errorCode")
    ga_error: Optional[GaError] = Field(default=None, alias="gaError")
    ga_error_list: Optional[List[GaError]] = Field(default=None, alias="gaErrorList")
    __properties: ClassVar[List[str]] = ["type", "title", "timestamp", "message", "details", "detailsMap", "errorCode", "gaError", "gaErrorList"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ErrorDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ga_error
        if self.ga_error:
            _dict['gaError'] = self.ga_error.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in ga_error_list (list)
        _items = []
        if self.ga_error_list:
            for _item_ga_error_list in self.ga_error_list:
                if _item_ga_error_list:
                    _items.append(_item_ga_error_list.to_dict())
            _dict['gaErrorList'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ErrorDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "title": obj.get("title"),
            "timestamp": obj.get("timestamp"),
            "message": obj.get("message"),
            "details": obj.get("details"),
            "detailsMap": obj.get("detailsMap"),
            "errorCode": obj.get("errorCode"),
            "gaError": GaError.from_dict(obj["gaError"]) if obj.get("gaError") is not None else None,
            "gaErrorList": [GaError.from_dict(_item) for _item in obj["gaErrorList"]] if obj.get("gaErrorList") is not None else None
        })
        return _obj


