# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from order_capture_client.models.pick_up_point_metadata import PickUpPointMetadata
from order_capture_client.models.pup_price import PUPPrice
from order_capture_client.models.time_windows_dto import TimeWindowsDto
from typing import Optional, Set
from typing_extensions import Self

class PickUpPointDto(BaseModel):
    """
    List of possible pick up points with details
    """ # noqa: E501
    oc_pupid: Optional[StrictStr] = Field(default=None, description="It describes the order capture generated UUID for a pick up point. Consumer must use this in API", alias="ocPUPId")
    sto: Optional[StrictStr] = Field(default=None, description="This information is only available for collect at store pick up points. This is subject to change in the future.")
    metadata: Optional[PickUpPointMetadata] = None
    price: Optional[PUPPrice] = None
    id: Optional[StrictStr] = Field(default=None, description="iSOM provided ID for a pick up point")
    name: Optional[StrictStr] = Field(default=None, description="iSOM provided name for a pick up point")
    identifier: Optional[StrictStr] = Field(default=None, description="iSOM provided identifier for a pick up point")
    lsc: Optional[StrictStr] = Field(default=None, description="iSOM provided merge node")
    latitude: Optional[StrictStr] = Field(default=None, description="iSOM provided co-ordinates i.e. latitude and longitude")
    longitude: Optional[StrictStr] = Field(default=None, description="iSOM provided co-ordinates i.e. latitude and longitude")
    opening_hours_mon_time: Optional[StrictStr] = Field(default=None, description="iSOM provided opening hours for each day. May included comma separated time range if collection point has more than 1 range of opening hours within a day", alias="openingHoursMonTime")
    opening_hours_tue_time: Optional[StrictStr] = Field(default=None, description="iSOM provided opening hours for each day. May included comma separated time range if collection point has more than 1 range of opening hours within a day", alias="openingHoursTueTime")
    opening_hours_wed_time: Optional[StrictStr] = Field(default=None, description="iSOM provided opening hours for each day. May included comma separated time range if collection point has more than 1 range of opening hours within a day", alias="openingHoursWedTime")
    opening_hours_thu_time: Optional[StrictStr] = Field(default=None, description="iSOM provided opening hours for each day. May included comma separated time range if collection point has more than 1 range of opening hours within a day", alias="openingHoursThuTime")
    opening_hours_fri_time: Optional[StrictStr] = Field(default=None, description="iSOM provided opening hours for each day. May included comma separated time range if collection point has more than 1 range of opening hours within a day", alias="openingHoursFriTime")
    opening_hours_sat_time: Optional[StrictStr] = Field(default=None, description="iSOM provided opening hours for each day. May included comma separated time range if collection point has more than 1 range of opening hours within a day", alias="openingHoursSatTime")
    opening_hours_sun_time: Optional[StrictStr] = Field(default=None, description="iSOM provided opening hours for each day. May included comma separated time range if collection point has more than 1 range of opening hours within a day", alias="openingHoursSunTime")
    country: Optional[StrictStr] = Field(default=None, description="iSOM provided Country Code")
    zip_code: Optional[StrictStr] = Field(default=None, description="iSOM provided Zipcode", alias="zipCode")
    city: Optional[StrictStr] = Field(default=None, description="iSOM provided City")
    state: Optional[StrictStr] = Field(default=None, description="iSOM provided State Code. It may not be available always and it depends on the country")
    address_line1: Optional[StrictStr] = Field(default=None, description="iSOM provided Address lines", alias="addressLine1")
    address_line2: Optional[StrictStr] = Field(default=None, description="iSOM provided Address lines", alias="addressLine2")
    address_line3: Optional[StrictStr] = Field(default=None, description="iSOM provided Address lines", alias="addressLine3")
    address_line4: Optional[StrictStr] = Field(default=None, description="iSOM provided Address lines", alias="addressLine4")
    distance: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="iSOM provided Distance to customer zip code")
    time_windows: Optional[TimeWindowsDto] = Field(default=None, alias="timeWindows")
    __properties: ClassVar[List[str]] = ["ocPUPId", "sto", "metadata", "price", "id", "name", "identifier", "lsc", "latitude", "longitude", "openingHoursMonTime", "openingHoursTueTime", "openingHoursWedTime", "openingHoursThuTime", "openingHoursFriTime", "openingHoursSatTime", "openingHoursSunTime", "country", "zipCode", "city", "state", "addressLine1", "addressLine2", "addressLine3", "addressLine4", "distance", "timeWindows"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PickUpPointDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # override the default output from pydantic by calling `to_dict()` of price
        if self.price:
            _dict['price'] = self.price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of time_windows
        if self.time_windows:
            _dict['timeWindows'] = self.time_windows.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PickUpPointDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ocPUPId": obj.get("ocPUPId"),
            "sto": obj.get("sto"),
            "metadata": PickUpPointMetadata.from_dict(obj["metadata"]) if obj.get("metadata") is not None else None,
            "price": PUPPrice.from_dict(obj["price"]) if obj.get("price") is not None else None,
            "id": obj.get("id"),
            "name": obj.get("name"),
            "identifier": obj.get("identifier"),
            "lsc": obj.get("lsc"),
            "latitude": obj.get("latitude"),
            "longitude": obj.get("longitude"),
            "openingHoursMonTime": obj.get("openingHoursMonTime"),
            "openingHoursTueTime": obj.get("openingHoursTueTime"),
            "openingHoursWedTime": obj.get("openingHoursWedTime"),
            "openingHoursThuTime": obj.get("openingHoursThuTime"),
            "openingHoursFriTime": obj.get("openingHoursFriTime"),
            "openingHoursSatTime": obj.get("openingHoursSatTime"),
            "openingHoursSunTime": obj.get("openingHoursSunTime"),
            "country": obj.get("country"),
            "zipCode": obj.get("zipCode"),
            "city": obj.get("city"),
            "state": obj.get("state"),
            "addressLine1": obj.get("addressLine1"),
            "addressLine2": obj.get("addressLine2"),
            "addressLine3": obj.get("addressLine3"),
            "addressLine4": obj.get("addressLine4"),
            "distance": obj.get("distance"),
            "timeWindows": TimeWindowsDto.from_dict(obj["timeWindows"]) if obj.get("timeWindows") is not None else None
        })
        return _obj


