# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from order_capture_client.models.question_set import QuestionSet
from typing import Optional, Set
from typing_extensions import Self

class Questions(BaseModel):
    """
    Questions
    """ # noqa: E501
    delivery_question: Optional[List[QuestionSet]] = Field(default=None, description="It describes the set of delivery questions for selected delivery service. The question set contains questions for different types of living", alias="deliveryQuestion")
    service_question: Optional[List[QuestionSet]] = Field(default=None, description="It describes the set of service questions for selected delivery service. The question set contains questions for different types of living", alias="serviceQuestion")
    __properties: ClassVar[List[str]] = ["deliveryQuestion", "serviceQuestion"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Questions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in delivery_question (list)
        _items = []
        if self.delivery_question:
            for _item_delivery_question in self.delivery_question:
                if _item_delivery_question:
                    _items.append(_item_delivery_question.to_dict())
            _dict['deliveryQuestion'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in service_question (list)
        _items = []
        if self.service_question:
            for _item_service_question in self.service_question:
                if _item_service_question:
                    _items.append(_item_service_question.to_dict())
            _dict['serviceQuestion'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Questions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "deliveryQuestion": [QuestionSet.from_dict(_item) for _item in obj["deliveryQuestion"]] if obj.get("deliveryQuestion") is not None else None,
            "serviceQuestion": [QuestionSet.from_dict(_item) for _item in obj["serviceQuestion"]] if obj.get("serviceQuestion") is not None else None
        })
        return _obj


