# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from order_capture_client.models.price import Price
from order_capture_client.models.removal_service_metadata import RemovalServiceMetadata
from typing import Optional, Set
from typing_extensions import Self

class RemovalServiceItem(BaseModel):
    """
    RemovalServiceItem
    """ # noqa: E501
    line_id: Optional[StrictStr] = Field(default=None, alias="lineId")
    service_item_no: Optional[StrictStr] = Field(default=None, alias="serviceItemNo")
    service_product_id: Optional[StrictStr] = Field(default=None, alias="serviceProductId")
    price: Optional[Price] = None
    provider: Optional[StrictStr] = None
    quantity: Optional[StrictInt] = None
    price_calculation_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="priceCalculationValue")
    taxation_info: Optional[StrictStr] = Field(default=None, alias="taxationInfo")
    removal_service_metadata: Optional[RemovalServiceMetadata] = Field(default=None, alias="removalServiceMetadata")
    pay_to_provider: Optional[StrictBool] = Field(default=None, alias="payToProvider")
    __properties: ClassVar[List[str]] = ["lineId", "serviceItemNo", "serviceProductId", "price", "provider", "quantity", "priceCalculationValue", "taxationInfo", "removalServiceMetadata", "payToProvider"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RemovalServiceItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of price
        if self.price:
            _dict['price'] = self.price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of removal_service_metadata
        if self.removal_service_metadata:
            _dict['removalServiceMetadata'] = self.removal_service_metadata.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RemovalServiceItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "lineId": obj.get("lineId"),
            "serviceItemNo": obj.get("serviceItemNo"),
            "serviceProductId": obj.get("serviceProductId"),
            "price": Price.from_dict(obj["price"]) if obj.get("price") is not None else None,
            "provider": obj.get("provider"),
            "quantity": obj.get("quantity"),
            "priceCalculationValue": obj.get("priceCalculationValue"),
            "taxationInfo": obj.get("taxationInfo"),
            "removalServiceMetadata": RemovalServiceMetadata.from_dict(obj["removalServiceMetadata"]) if obj.get("removalServiceMetadata") is not None else None,
            "payToProvider": obj.get("payToProvider")
        })
        return _obj


