# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from order_capture_client.models.so_error_dto import SOErrorDto
from order_capture_client.models.so_platform_create_info_dto import SOPlatformCreateInfoDto
from typing import Optional, Set
from typing_extensions import Self

class SOPlatformCreateResponseDto(BaseModel):
    """
    SOPlatformCreateResponseDto
    """ # noqa: E501
    status: StrictStr = Field(description="This property indicates the status of quote create. In async mode, if the status is available, then it will be COMPLETED. Otherwise it will be PENDING until a timeout and TIME_OUT if there is no result for a configured interval")
    platform_create_info: Optional[SOPlatformCreateInfoDto] = Field(default=None, alias="platformCreateInfo")
    errors: Optional[List[SOErrorDto]] = None
    __properties: ClassVar[List[str]] = ["status", "platformCreateInfo", "errors"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['PENDING', 'CREATED', 'UNCERTAIN', 'TIME_OUT']):
            raise ValueError("must be one of enum values ('PENDING', 'CREATED', 'UNCERTAIN', 'TIME_OUT')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SOPlatformCreateResponseDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of platform_create_info
        if self.platform_create_info:
            _dict['platformCreateInfo'] = self.platform_create_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in errors (list)
        _items = []
        if self.errors:
            for _item_errors in self.errors:
                if _item_errors:
                    _items.append(_item_errors.to_dict())
            _dict['errors'] = _items
        # set to None if platform_create_info (nullable) is None
        # and model_fields_set contains the field
        if self.platform_create_info is None and "platform_create_info" in self.model_fields_set:
            _dict['platformCreateInfo'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SOPlatformCreateResponseDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "platformCreateInfo": SOPlatformCreateInfoDto.from_dict(obj["platformCreateInfo"]) if obj.get("platformCreateInfo") is not None else None,
            "errors": [SOErrorDto.from_dict(_item) for _item in obj["errors"]] if obj.get("errors") is not None else None
        })
        return _obj


