# coding: utf-8

"""
    OrderCapture

    Order Capture Checkout API Definitions

    The version of the OpenAPI document: v2.0.8
    Contact: dl.order.capture.dev.se@ingka.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from order_capture_client.models.tax_jurisdiction import TaxJurisdiction
from typing import Optional, Set
from typing_extensions import Self

class Tax(BaseModel):
    """
    Tax
    """ # noqa: E501
    tax_jurisdiction: Optional[TaxJurisdiction] = Field(default=None, alias="taxJurisdiction")
    type: Optional[StrictStr] = None
    code: Optional[StrictStr] = None
    tax_percentage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="taxPercentage")
    tax_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="taxAmount")
    taxable_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="taxableAmount")
    __properties: ClassVar[List[str]] = ["taxJurisdiction", "type", "code", "taxPercentage", "taxAmount", "taxableAmount"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Tax from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of tax_jurisdiction
        if self.tax_jurisdiction:
            _dict['taxJurisdiction'] = self.tax_jurisdiction.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Tax from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "taxJurisdiction": TaxJurisdiction.from_dict(obj["taxJurisdiction"]) if obj.get("taxJurisdiction") is not None else None,
            "type": obj.get("type"),
            "code": obj.get("code"),
            "taxPercentage": obj.get("taxPercentage"),
            "taxAmount": obj.get("taxAmount"),
            "taxableAmount": obj.get("taxableAmount")
        })
        return _obj


