# coding: utf-8

"""
    Sales Item API

    Get information for items in different contexts. Note that this is an extendable interface that might introduce new types without increase in major version including new values in enumerations. 

    The version of the OpenAPI document: 1.45.0
    Contact: paul.eriksson@ingka.ikea.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from salesitem_client.api.availability_classification_api import AvailabilityClassificationApi


class TestAvailabilityClassificationApi(unittest.TestCase):
    """AvailabilityClassificationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AvailabilityClassificationApi()

    def tearDown(self) -> None:
        pass

    def test_get_item_availability_classifications(self) -> None:
        """Test case for get_item_availability_classifications

        Get availability classification information (operational range) of the choosen class unit. Used to get a complete list of items based on at least one classification type. Please note that you have to specify either the `itemNos` query parameter or the `type` query parameter.
        """
        pass


if __name__ == '__main__':
    unittest.main()
