# coding: utf-8

"""
    Sales Item API

    Get information for items in different contexts. Note that this is an extendable interface that might introduce new types without increase in major version including new values in enumerations. 

    The version of the OpenAPI document: 1.45.0
    Contact: paul.eriksson@ingka.ikea.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from salesitem_client.models.media_variant import MediaVariant

class TestMediaVariant(unittest.TestCase):
    """MediaVariant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MediaVariant:
        """Test MediaVariant
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MediaVariant`
        """
        model = MediaVariant()
        if include_optional:
            return MediaVariant(
                file_mime_type = 'image/jpeg',
                file_name = '0602358_PE680291_S1.JPG',
                height = 200,
                href = 'https://www.ikea.com/se/sv/images/products/gjoera-bed-frame__0666552_PH154359_S4.JPG',
                quality = 'S2',
                width = 200
            )
        else:
            return MediaVariant(
        )
        """

    def testMediaVariant(self):
        """Test MediaVariant"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
