# coding: utf-8

"""
    Sales Item API

    Get information for items in different contexts. Note that this is an extendable interface that might introduce new types without increase in major version including new values in enumerations. 

    The version of the OpenAPI document: 1.45.0
    Contact: paul.eriksson@ingka.ikea.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from salesitem_client.models.item_benefit import ItemBenefit

class TestItemBenefit(unittest.TestCase):
    """ItemBenefit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemBenefit:
        """Test ItemBenefit
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemBenefit`
        """
        model = ItemBenefit()
        if include_optional:
            return ItemBenefit(
                header = 'A safe lock',
                name = 'PATRULL drawer/cabinet catch',
                subject = 'Function/solution',
                text = 'When your child feels like exploring the contents of cabinets and drawers PATRULL drawer/cabinet catch puts a stop to all attempts. But its easy for grown-ups to open - all you do is press lightly on the catch.'
            )
        else:
            return ItemBenefit(
        )
        """

    def testItemBenefit(self):
        """Test ItemBenefit"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
