# coding: utf-8

"""
    Sales Item API

    Get information for items in different contexts. Note that this is an extendable interface that might introduce new types without increase in major version including new values in enumerations. 

    The version of the OpenAPI document: 1.45.0
    Contact: paul.eriksson@ingka.ikea.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from salesitem_client.models.sales_price_unit_price_unit_price_texts import SalesPriceUnitPriceUnitPriceTexts

class TestSalesPriceUnitPriceUnitPriceTexts(unittest.TestCase):
    """SalesPriceUnitPriceUnitPriceTexts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SalesPriceUnitPriceUnitPriceTexts:
        """Test SalesPriceUnitPriceUnitPriceTexts
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SalesPriceUnitPriceUnitPriceTexts`
        """
        model = SalesPriceUnitPriceUnitPriceTexts()
        if include_optional:
            return SalesPriceUnitPriceUnitPriceTexts(
                country_code = '',
                language_code = '',
                unit_text_imperial = '',
                unit_text_metric = ''
            )
        else:
            return SalesPriceUnitPriceUnitPriceTexts(
        )
        """

    def testSalesPriceUnitPriceUnitPriceTexts(self):
        """Test SalesPriceUnitPriceUnitPriceTexts"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
