# coding: utf-8

"""
    Sales Item API

    Get information for items in different contexts. Note that this is an extendable interface that might introduce new types without increase in major version including new values in enumerations. 

    The version of the OpenAPI document: 1.45.0
    Contact: paul.eriksson@ingka.ikea.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from salesitem_client.models.communication_response import CommunicationResponse

class TestCommunicationResponse(unittest.TestCase):
    """CommunicationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommunicationResponse:
        """Test CommunicationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommunicationResponse`
        """
        model = CommunicationResponse()
        if include_optional:
            return CommunicationResponse(
                data = [
                    salesitem_client.models.item_communication.itemCommunication(
                        add_ons = [
                            salesitem_client.models.add_on.addOn(
                                item_key = salesitem_client.models.item_key.itemKey(
                                    item_no = '00263850', 
                                    item_type = 'ART', ), 
                                relation = 'ADDS_ADDITIONAL_FUNCTION', 
                                main_product_type = salesitem_client.models.main_product_type.mainProductType(
                                    name = '', 
                                    false = '', ), 
                                catalogue_references = [
                                    salesitem_client.models.catalogue_reference.catalogueReference(
                                        catalogue_id = 'products', 
                                        category_id = 'fu001', )
                                    ], )
                            ], 
                        business_structure = salesitem_client.models.business_structure.businessStructure(
                            home_furnishing_business_name = 'Secondary storage', 
                            home_furnishing_business_no = '19', 
                            product_area_name = 'Secondary storage units', 
                            product_area_no = '1912', 
                            product_range_area_name = 'Secondary storage range', 
                            product_range_area_no = '191', ), 
                        catalogue_references = [
                            salesitem_client.models.catalogue_reference.catalogueReference(
                                catalogue_id = 'products', 
                                category_id = 'fu001', )
                            ], 
                        child_items = [
                            salesitem_client.models.item_child.itemChild(
                                complementary_items = [
                                    salesitem_client.models.complementary_item.complementaryItem(
                                        type = 'MUST_BE_COMPLETED_WITH', )
                                    ], 
                                filter_classes = [
                                    'rugs'
                                    ], 
                                is_assembly_required = True, 
                                is_breath_taking_item = True, 
                                is_new = True, 
                                item_key = salesitem_client.models.item_key.itemKey(
                                    item_no = '00263850', 
                                    item_type = 'ART', ), 
                                item_key_global = , 
                                last_chance = salesitem_client.models.last_chance.lastChance(
                                    value = True, ), 
                                localised_communications = [
                                    salesitem_client.models.localised.localised(
                                        acknowledgement = salesitem_client.models.acknowledgement.acknowledgement(
                                            is_needed = True, ), 
                                        assembly_effort = [
                                            salesitem_client.models.assembly_effort.assemblyEffort(
                                                estimated_time = salesitem_client.models.estimated_time.estimatedTime(
                                                    unit = 'MINUTES', 
                                                    value = 30, ), 
                                                required_persons = 2, 
                                                required_tools = [
                                                    salesitem_client.models.required_tool.requiredTool(
                                                        included_in_package = True, 
                                                        name = 'Allen Key', 
                                                        type = 'TOOL_ADJUSTABLE_PLIERS', )
                                                    ], 
                                                type = 'CUSTOMER_ASSEMBLY', )
                                            ], 
                                        attachments = [
                                            salesitem_client.models.item_attachment.itemAttachment(
                                                href = 'https://www.ikea.com/gb/en/doc/assembly_instructions/patrull__aa-428912-3_pub.pdf', 
                                                type = 'ASSEMBLY_INSTRUCTIONS', )
                                            ], 
                                        backoff_to_hero = salesitem_client.models.backoff_to_hero.backoffToHero(
                                            heroes = [
                                                salesitem_client.models.item_hero.itemHero(
                                                    name = 'IVAR NNN 1 sec/shelves 89x30x179 pine', 
                                                    upsell_arguments = [
                                                        salesitem_client.models.upsell_argument.upsellArgument(
                                                            long_text = 'You can move shelves and adapt the spacing to suit your needs', 
                                                            short_text = 'Adjustable shelves', )
                                                        ], )
                                                ], ), 
                                        benefit_summary = 'Like a dream – a silky-soft duvet cover with a beautiful  luster. Sateen-woven from the finest yarn made of lyocell  and sustainably grown cotton. Natural materials that feel  good against your skin.
', 
                                        benefits = [
                                            'Keeps the contents warm for longer and the outside cool, thanks to the double-walled glass.'
                                            ], 
                                        care_instructions = [
                                            salesitem_client.models.item_care_instruction.itemCareInstruction(
                                                care_instruction_header = 'Cushion', 
                                                care_instruction_texts = [
                                                    salesitem_client.models.care_instruction_text.careInstructionText(
                                                        care_instruction_text = 'Do not wash.', )
                                                    ], 
                                                product_type_text = 'Inner back cushion/inner seat cushion', )
                                            ], 
                                        certification_media = [
                                            salesitem_client.models.certification_media.certificationMedia(
                                                alt_text = 'IKEA Stofftier Djungelskog 00402808 von Stiftung Warentest mit gut (1,7) ausgezeichnet Ausgabe 11/2020', 
                                                display_text = 'Von Stiftung Warentest mit gut (1,7) ausgezeichnet', 
                                                media_info_url = 'www.test.de', 
                                                type = 'MEDIA_TYPE_BEST_IN_TEST, MEDIA_TYPE_CONSUMER_AWARDS, MEDIA_TYPE_DESIGN_AWARDS, MEDIA_TYPE_MARKET_SPECIFIC_SAFETY_STANDARDS, MEDIA_TYPE_INDUSTRY_TESTING_CERTIFICATIONS', 
                                                variants = [
                                                    salesitem_client.models.media_variant.mediaVariant(
                                                        file_mime_type = 'image/jpeg', 
                                                        file_name = '0602358_PE680291_S1.JPG', 
                                                        height = 200, 
                                                        href = 'https://www.ikea.com/se/sv/images/products/gjoera-bed-frame__0666552_PH154359_S4.JPG', 
                                                        quality = 'S2', 
                                                        width = 200, )
                                                    ], )
                                            ], 
                                        compliance = [
                                            salesitem_client.models.compliance.compliance(
                                                name = '색상', 
                                                type = 'COLOUR', 
                                                value = '제품명 또는 이미지 참조', )
                                            ], 
                                        compliance_information = [
                                            salesitem_client.models.compliance_information.complianceInformation(
                                                sections = [
                                                    salesitem_client.models.compliance_information_section.complianceInformationSection(
                                                        heading = 'Holzart', 
                                                        urls = [
                                                            salesitem_client.models.compliance_url.complianceUrl(
                                                                text = 'DTSCCalSAFER', 
                                                                url = 'https://calsafer.dtsc.ca.gov/cms/search/?type=Chemical', )
                                                            ], 
                                                        values = [
                                                            'Buche (Fagus sylvatica); Land des Holzeinschlags: Republik Kroatien, SLOWAKEI, SLOWENIEN'
                                                            ], )
                                                    ], 
                                                type = 'CALIFORNIA_AB_1200', )
                                            ], 
                                        country_code = 'US', 
                                        designers = [
                                            salesitem_client.models.designer.designer(
                                                id = '11756', 
                                                name = 'Ehlen Johansson', )
                                            ], 
                                        display_unit = salesitem_client.models.display_unit.displayUnit(
                                            type = 'WEIGHT', 
                                            unit_information = salesitem_client.models.unit_information.unitInformation(
                                                unit_imperial = 'oz', 
                                                unit_imperial_value = '5.29', 
                                                unit_metric = 'g', 
                                                unit_metric_value = '150', ), ), 
                                        environment_texts = [
                                            salesitem_client.models.item_environment_text.itemEnvironmentText(
                                                product_type_text = 'Standard hinges', 
                                                text = 'Product is possible to recycle or use for energy recovery, if available in your community.', )
                                            ], 
                                        filter_information = salesitem_client.models.filter_information.filterInformation(
                                            class_filters = [
                                                salesitem_client.models.class_filter.classFilter(
                                                    id = '11211', 
                                                    name = 'Material', )
                                                ], 
                                            measurement_filters = [
                                                salesitem_client.models.measurement_filter.measurementFilter(
                                                    text_imperial = '55 1/8 "', 
                                                    text_metric = '140 cm', 
                                                    type = 'WIDTH', 
                                                    type_name = 'Width', 
                                                    unit_imperial = 'inch', 
                                                    unit_metric = 'cm', 
                                                    value_imperial = '55 1/8', 
                                                    value_metric = '140', )
                                                ], 
                                            reference_measurement_filter = salesitem_client.models.reference_measurement_filter.referenceMeasurementFilter(
                                                imperial = '55 1/8x74 "', 
                                                metric = '140x188 cm', 
                                                id = '140x188', ), ), 
                                        full_length_texts = salesitem_client.models.full_length_text.fullLengthText(
                                            subject_id = '000000000000008', 
                                            texts = [
                                                salesitem_client.models.full_length_text_detailed.fullLengthTextDetailed(
                                                    id = 'MAIN_HEADLINE', 
                                                    value = 'A better everyday one cup at a time', )
                                                ], ), 
                                        good_to_knows = [
                                            salesitem_client.models.item_good_to_know.itemGoodToKnow(
                                                text = 'High cabinet frame with ventilated grid, doors, plinth and handles are sold separately.', 
                                                type = 'Sold separately', )
                                            ], 
                                        item_name_local = 'BEKANT desk 160x80 white stained oak veneer/white', 
                                        key_benefits = [
                                            salesitem_client.models.item_key_benefit.itemKeyBenefit(
                                                heading_text = 'Noise Level', 
                                                text = 'Noise level at max. exhaust speed: 60 dB (A)', 
                                                type = 'KEY_BENEFIT_NOISE_LEVEL', 
                                                unit_of_measure = 'dB (A)', 
                                                value = '60', )
                                            ], 
                                        language_code = 'en', 
                                        long_benefits = [
                                            salesitem_client.models.item_benefit.itemBenefit(
                                                header = 'A safe lock', 
                                                name = 'PATRULL drawer/cabinet catch', 
                                                subject = 'Function/solution', 
                                                text = 'When your child feels like exploring the contents of cabinets and drawers PATRULL drawer/cabinet catch puts a stop to all attempts. But its easy for grown-ups to open - all you do is press lightly on the catch.', )
                                            ], 
                                        manufacturer = 'IKEA', 
                                        materials = [
                                            salesitem_client.models.item_customer_material.itemCustomerMaterial(
                                                part_materials = [
                                                    salesitem_client.models.item_part_material.itemPartMaterial(
                                                        material_text = '100% cotton', 
                                                        part_text = 'Total composition:', )
                                                    ], 
                                                product_type_text = 'Cover for 2-seat section', )
                                            ], 
                                        measurements = salesitem_client.models.item_measurements.itemMeasurements(
                                            detailed_measurements = [
                                                salesitem_client.models.detailed_measurement.detailedMeasurement(
                                                    text_imperial = '31 1/2 "', 
                                                    text_metric = '80 cm', 
                                                    type = 'HEIGHT_INCLUDING_BACK_CHUSHIONS', 
                                                    type_name = 'Height including back cushions', )
                                                ], 
                                            reference_measurements = [
                                                salesitem_client.models.reference_measurement.referenceMeasurement(
                                                    imperial = '7/3 cu.ft', 
                                                    metric = '210/79 l', )
                                                ], ), 
                                        media = [
                                            salesitem_client.models.item_media.itemMedia(
                                                action = salesitem_client.models.video_action.videoAction(
                                                    file_mime_type = 'image/jpeg', 
                                                    file_name = 'fe000181_890x500_00h_00m_01s.jpg', 
                                                    height = 500, 
                                                    href = 'https://mmapi.ikea.com/im/productfilms/images/fe000181_890x500_00h_00m_01s.jpg', 
                                                    width = 890, ), 
                                                alt_text = 'LANDSKRONA sofa with chaise long', 
                                                transcript = 'You don’t have to choose between a functional interior or clean exterior. This drawer front lets you have several smaller drawers behind a larger front or door – for both smart storage and a uniform look.', 
                                                id = '0602358', 
                                                information_dots = [
                                                    salesitem_client.models.media_information_dot.mediaInformationDot(
                                                        coordinates = salesitem_client.models.media_information_dot_coordinates.mediaInformationDotCoordinates(
                                                            x = 52.7, 
                                                            y = 34, ), 
                                                        header = 'Standard foam', 
                                                        icon = 'mattress-foam', 
                                                        text = 'Gives you all-over support and comfort.', )
                                                    ], 
                                                name = 'LANDSKRONA so3 w chs lng/Grann/Bomstad gld-br/wood MPP', 
                                                pe_no = 'PE680291', 
                                                poster = [
                                                    salesitem_client.models.video_poster.videoPoster(
                                                        file_mime_type = 'image/jpeg', 
                                                        file_name = 'fe000181_1920x1080_00h_00m_01s.jpg', 
                                                        height = 1080, 
                                                        href = 'https://mmapi.ikea.com/im/productfilms/images/fe000181_1920x1080_00h_00m_01s.jpg', 
                                                        quality = 'S5', 
                                                        width = 1920, )
                                                    ], 
                                                snapshots = [
                                                    salesitem_client.models.video_snapshot.videoSnapshot(
                                                        file_mime_type = 'image/jpeg', 
                                                        file_name = 'fe000181_114x64_00h_00m_00s.jpg', 
                                                        frame = 0, 
                                                        height = 114, 
                                                        href = 'https://mmapi.ikea.com/im/productfilms/images/fe000181_114x64_00h_00m_00s.jpg', 
                                                        width = 64, )
                                                    ], 
                                                thumbnail = salesitem_client.models.video_thumbnail.videoThumbnail(
                                                    file_mime_type = 'image/jpeg', 
                                                    file_name = 'fe000181_890x500_00h_00m_01s.jpg?imPolicy=thumbnail', 
                                                    height = 250, 
                                                    href = 'https://mmapi.ikea.com/im/productfilms/images/fe000181_890x500_00h_00m_01s.jpg?imPolicy=thumbnail', 
                                                    width = 250, ), 
                                                type_name = 'MAIN_PRODUCT_IMAGE', 
                                                type_no = '00001', )
                                            ], 
                                        package_measurements = [
                                            salesitem_client.models.item_package_measure.itemPackageMeasure(
                                                pack_no = 1, 
                                                text_imperial = '3 "', 
                                                text_metric = '8 cm', 
                                                type = 'LENGTH', 
                                                type_name = 'Length', 
                                                unit_imperial = '"', 
                                                unit_metric = 'cm', 
                                                value_imperial = '3', 
                                                value_metric = '8', )
                                            ], 
                                        product_name = 'VIMLE', 
                                        product_tags = [
                                            salesitem_client.models.locale_product_tag.localeProductTag(
                                                name = 'SLEEP_ON_IT_DAYS', )
                                            ], 
                                        product_type = salesitem_client.models.product_type.productType(
                                            id = '10210', 
                                            name = '2-seat sofa', ), 
                                        seo_slug = 'vimle-2-seat-sofa', 
                                        technical_compliance = [
                                            salesitem_client.models.technical_compliance.technicalCompliance(
                                                heading = 'Kostnadsspann alla modeller', 
                                                heading_global = 'Cost ranges All models', 
                                                heading_type = 'WATER_CONSUMPTION', 
                                                value = '2 - 3', )
                                            ], 
                                        technical_information = salesitem_client.models.technical_information.technicalInformation(
                                            information_groups = [
                                                salesitem_client.models.technical_information_group.technicalInformationGroup(
                                                    heading_no = '00033', 
                                                    heading_text = 'General', 
                                                    information_parts = [
                                                        salesitem_client.models.technical_information_part.technicalInformationPart(
                                                            explanatory_text = '', 
                                                            legal = True, 
                                                            range_no = '00004', 
                                                            range_text = 'Fridges/Freezers', 
                                                            text = 'Energy efficiency class', 
                                                            text_imperial = '', 
                                                            text_metric = 'A++', 
                                                            text_no = '00033', 
                                                            unit_imperial = '', 
                                                            unit_metric = '', 
                                                            value_imperial = '', 
                                                            value_metric = 'A++', )
                                                        ], )
                                                ], ), 
                                        valid_design = salesitem_client.models.valid_design.validDesign(
                                            text = 'Tallmyra black/gray', ), 
                                        warnings = [
                                            salesitem_client.models.warning.warning(
                                                type = 'CHOKING_HAZARD', )
                                            ], 
                                        benefits_as_is = [
                                            'Keeps the contents warm for longer and the outside cool, thanks to the double-walled glass.'
                                            ], 
                                        benefit_summary_as_is = 'Like a dream – a silky-soft duvet cover with a beautiful  luster. Sateen-woven from the finest yarn made of lyocell  and sustainably grown cotton. Natural materials that feel  good against your skin.
', )
                                    ], 
                                news = salesitem_client.models.news.news(
                                    valid_from = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                    valid_to = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                    value = True, ), 
                                number_of_packages = 3, 
                                product_name_global = 'VIMLE', 
                                product_tags = [
                                    salesitem_client.models.product_tag.productTag(
                                        name = 'NEW', 
                                        valid_from = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                        valid_to = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                                    ], 
                                product_type_classes = [
                                    'sofas'
                                    ], 
                                quantity = 1, 
                                style_group = 'IKEA Multi', 
                                unit_code = 'METER', )
                            ], 
                        class_unit_key = salesitem_client.models.class_unit_key.classUnitKey(
                            class_unit_code = '445', 
                            class_unit_type = 'STO', ), 
                        complementary_items = [
                            salesitem_client.models.complementary_item.complementaryItem(
                                type = 'MUST_BE_COMPLETED_WITH', )
                            ], 
                        filter_classes = [
                            'rugs'
                            ], 
                        generic_product = salesitem_client.models.generic_product.genericProduct(
                            gpr_no = '03067', ), 
                        is_assembly_required = True, 
                        is_breath_taking_item = True, 
                        is_new = True, 
                        item_key = , 
                        item_key_global = , 
                        kitchen_unit = salesitem_client.models.kitchen_unit.kitchenUnit(
                            value = True, ), 
                        last_chance = salesitem_client.models.last_chance.lastChance(
                            value = True, ), 
                        localised_communications = [
                            salesitem_client.models.localised.localised(
                                benefit_summary = 'Like a dream – a silky-soft duvet cover with a beautiful  luster. Sateen-woven from the finest yarn made of lyocell  and sustainably grown cotton. Natural materials that feel  good against your skin.
', 
                                item_name_local = 'BEKANT desk 160x80 white stained oak veneer/white', 
                                benefit_summary_as_is = 'Like a dream – a silky-soft duvet cover with a beautiful  luster. Sateen-woven from the finest yarn made of lyocell  and sustainably grown cotton. Natural materials that feel  good against your skin.
', )
                            ], 
                        news = salesitem_client.models.news.news(
                            valid_from = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            valid_to = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            value = True, ), 
                        number_of_packages = 3, 
                        presentation_group_code = 'ME/FÖ 140', 
                        price_quality_classification = 'HIGH', 
                        product_name_global = 'VIMLE', 
                        product_tags = [
                            salesitem_client.models.product_tag.productTag(
                                name = 'NEW', 
                                valid_from = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                valid_to = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                            ], 
                        product_type_classes = [
                            'sofas'
                            ], 
                        product_view_template = salesitem_client.models.product_view_template.productViewTemplate(
                            type = 'TECHNICAL', 
                            value = 'LOW', ), 
                        professional_assembly_time = salesitem_client.models.professional_assembly_time.professionalAssemblyTime(
                            unit = 'MINUTES', 
                            value = 120, ), 
                        service_product_relations = [
                            salesitem_client.models.service_product_relation.serviceProductRelation(
                                hide_service_from_customer = True, 
                                is_co_worker_assistance_needed = True, 
                                is_promoted = True, 
                                recommendation_rank = 1, 
                                relation_type = 'SOLD_WITH', 
                                service_key = , 
                                service_product_id = 'BASIC_KITCHEN_INSTALL', 
                                service_product_type = 'ASSEMBLY', )
                            ], 
                        style_group = 'IKEA Multi', 
                        unit_code = 'METER', 
                        experimental = [
                            salesitem_client.models.experimental_item.experimentalItem(
                                name = '', 
                                data = '', )
                            ], 
                        update_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                error = salesitem_client.models.status.status(
                    code = 56, 
                    details = [
                        {
                            'key' : None
                            }
                        ], 
                    message = '', ),
                trace_id = '8e893adf-c115-46bb-ab5d-378c177a096e'
            )
        else:
            return CommunicationResponse(
                data = [
                    salesitem_client.models.item_communication.itemCommunication(
                        add_ons = [
                            salesitem_client.models.add_on.addOn(
                                item_key = salesitem_client.models.item_key.itemKey(
                                    item_no = '00263850', 
                                    item_type = 'ART', ), 
                                relation = 'ADDS_ADDITIONAL_FUNCTION', 
                                main_product_type = salesitem_client.models.main_product_type.mainProductType(
                                    name = '', 
                                    false = '', ), 
                                catalogue_references = [
                                    salesitem_client.models.catalogue_reference.catalogueReference(
                                        catalogue_id = 'products', 
                                        category_id = 'fu001', )
                                    ], )
                            ], 
                        business_structure = salesitem_client.models.business_structure.businessStructure(
                            home_furnishing_business_name = 'Secondary storage', 
                            home_furnishing_business_no = '19', 
                            product_area_name = 'Secondary storage units', 
                            product_area_no = '1912', 
                            product_range_area_name = 'Secondary storage range', 
                            product_range_area_no = '191', ), 
                        catalogue_references = [
                            salesitem_client.models.catalogue_reference.catalogueReference(
                                catalogue_id = 'products', 
                                category_id = 'fu001', )
                            ], 
                        child_items = [
                            salesitem_client.models.item_child.itemChild(
                                complementary_items = [
                                    salesitem_client.models.complementary_item.complementaryItem(
                                        type = 'MUST_BE_COMPLETED_WITH', )
                                    ], 
                                filter_classes = [
                                    'rugs'
                                    ], 
                                is_assembly_required = True, 
                                is_breath_taking_item = True, 
                                is_new = True, 
                                item_key = salesitem_client.models.item_key.itemKey(
                                    item_no = '00263850', 
                                    item_type = 'ART', ), 
                                item_key_global = , 
                                last_chance = salesitem_client.models.last_chance.lastChance(
                                    value = True, ), 
                                localised_communications = [
                                    salesitem_client.models.localised.localised(
                                        acknowledgement = salesitem_client.models.acknowledgement.acknowledgement(
                                            is_needed = True, ), 
                                        assembly_effort = [
                                            salesitem_client.models.assembly_effort.assemblyEffort(
                                                estimated_time = salesitem_client.models.estimated_time.estimatedTime(
                                                    unit = 'MINUTES', 
                                                    value = 30, ), 
                                                required_persons = 2, 
                                                required_tools = [
                                                    salesitem_client.models.required_tool.requiredTool(
                                                        included_in_package = True, 
                                                        name = 'Allen Key', 
                                                        type = 'TOOL_ADJUSTABLE_PLIERS', )
                                                    ], 
                                                type = 'CUSTOMER_ASSEMBLY', )
                                            ], 
                                        attachments = [
                                            salesitem_client.models.item_attachment.itemAttachment(
                                                href = 'https://www.ikea.com/gb/en/doc/assembly_instructions/patrull__aa-428912-3_pub.pdf', 
                                                type = 'ASSEMBLY_INSTRUCTIONS', )
                                            ], 
                                        backoff_to_hero = salesitem_client.models.backoff_to_hero.backoffToHero(
                                            heroes = [
                                                salesitem_client.models.item_hero.itemHero(
                                                    name = 'IVAR NNN 1 sec/shelves 89x30x179 pine', 
                                                    upsell_arguments = [
                                                        salesitem_client.models.upsell_argument.upsellArgument(
                                                            long_text = 'You can move shelves and adapt the spacing to suit your needs', 
                                                            short_text = 'Adjustable shelves', )
                                                        ], )
                                                ], ), 
                                        benefit_summary = 'Like a dream – a silky-soft duvet cover with a beautiful  luster. Sateen-woven from the finest yarn made of lyocell  and sustainably grown cotton. Natural materials that feel  good against your skin.
', 
                                        benefits = [
                                            'Keeps the contents warm for longer and the outside cool, thanks to the double-walled glass.'
                                            ], 
                                        care_instructions = [
                                            salesitem_client.models.item_care_instruction.itemCareInstruction(
                                                care_instruction_header = 'Cushion', 
                                                care_instruction_texts = [
                                                    salesitem_client.models.care_instruction_text.careInstructionText(
                                                        care_instruction_text = 'Do not wash.', )
                                                    ], 
                                                product_type_text = 'Inner back cushion/inner seat cushion', )
                                            ], 
                                        certification_media = [
                                            salesitem_client.models.certification_media.certificationMedia(
                                                alt_text = 'IKEA Stofftier Djungelskog 00402808 von Stiftung Warentest mit gut (1,7) ausgezeichnet Ausgabe 11/2020', 
                                                display_text = 'Von Stiftung Warentest mit gut (1,7) ausgezeichnet', 
                                                media_info_url = 'www.test.de', 
                                                type = 'MEDIA_TYPE_BEST_IN_TEST, MEDIA_TYPE_CONSUMER_AWARDS, MEDIA_TYPE_DESIGN_AWARDS, MEDIA_TYPE_MARKET_SPECIFIC_SAFETY_STANDARDS, MEDIA_TYPE_INDUSTRY_TESTING_CERTIFICATIONS', 
                                                variants = [
                                                    salesitem_client.models.media_variant.mediaVariant(
                                                        file_mime_type = 'image/jpeg', 
                                                        file_name = '0602358_PE680291_S1.JPG', 
                                                        height = 200, 
                                                        href = 'https://www.ikea.com/se/sv/images/products/gjoera-bed-frame__0666552_PH154359_S4.JPG', 
                                                        quality = 'S2', 
                                                        width = 200, )
                                                    ], )
                                            ], 
                                        compliance = [
                                            salesitem_client.models.compliance.compliance(
                                                name = '색상', 
                                                type = 'COLOUR', 
                                                value = '제품명 또는 이미지 참조', )
                                            ], 
                                        compliance_information = [
                                            salesitem_client.models.compliance_information.complianceInformation(
                                                sections = [
                                                    salesitem_client.models.compliance_information_section.complianceInformationSection(
                                                        heading = 'Holzart', 
                                                        urls = [
                                                            salesitem_client.models.compliance_url.complianceUrl(
                                                                text = 'DTSCCalSAFER', 
                                                                url = 'https://calsafer.dtsc.ca.gov/cms/search/?type=Chemical', )
                                                            ], 
                                                        values = [
                                                            'Buche (Fagus sylvatica); Land des Holzeinschlags: Republik Kroatien, SLOWAKEI, SLOWENIEN'
                                                            ], )
                                                    ], 
                                                type = 'CALIFORNIA_AB_1200', )
                                            ], 
                                        country_code = 'US', 
                                        designers = [
                                            salesitem_client.models.designer.designer(
                                                id = '11756', 
                                                name = 'Ehlen Johansson', )
                                            ], 
                                        display_unit = salesitem_client.models.display_unit.displayUnit(
                                            type = 'WEIGHT', 
                                            unit_information = salesitem_client.models.unit_information.unitInformation(
                                                unit_imperial = 'oz', 
                                                unit_imperial_value = '5.29', 
                                                unit_metric = 'g', 
                                                unit_metric_value = '150', ), ), 
                                        environment_texts = [
                                            salesitem_client.models.item_environment_text.itemEnvironmentText(
                                                product_type_text = 'Standard hinges', 
                                                text = 'Product is possible to recycle or use for energy recovery, if available in your community.', )
                                            ], 
                                        filter_information = salesitem_client.models.filter_information.filterInformation(
                                            class_filters = [
                                                salesitem_client.models.class_filter.classFilter(
                                                    id = '11211', 
                                                    name = 'Material', )
                                                ], 
                                            measurement_filters = [
                                                salesitem_client.models.measurement_filter.measurementFilter(
                                                    text_imperial = '55 1/8 "', 
                                                    text_metric = '140 cm', 
                                                    type = 'WIDTH', 
                                                    type_name = 'Width', 
                                                    unit_imperial = 'inch', 
                                                    unit_metric = 'cm', 
                                                    value_imperial = '55 1/8', 
                                                    value_metric = '140', )
                                                ], 
                                            reference_measurement_filter = salesitem_client.models.reference_measurement_filter.referenceMeasurementFilter(
                                                imperial = '55 1/8x74 "', 
                                                metric = '140x188 cm', 
                                                id = '140x188', ), ), 
                                        full_length_texts = salesitem_client.models.full_length_text.fullLengthText(
                                            subject_id = '000000000000008', 
                                            texts = [
                                                salesitem_client.models.full_length_text_detailed.fullLengthTextDetailed(
                                                    id = 'MAIN_HEADLINE', 
                                                    value = 'A better everyday one cup at a time', )
                                                ], ), 
                                        good_to_knows = [
                                            salesitem_client.models.item_good_to_know.itemGoodToKnow(
                                                text = 'High cabinet frame with ventilated grid, doors, plinth and handles are sold separately.', 
                                                type = 'Sold separately', )
                                            ], 
                                        item_name_local = 'BEKANT desk 160x80 white stained oak veneer/white', 
                                        key_benefits = [
                                            salesitem_client.models.item_key_benefit.itemKeyBenefit(
                                                heading_text = 'Noise Level', 
                                                text = 'Noise level at max. exhaust speed: 60 dB (A)', 
                                                type = 'KEY_BENEFIT_NOISE_LEVEL', 
                                                unit_of_measure = 'dB (A)', 
                                                value = '60', )
                                            ], 
                                        language_code = 'en', 
                                        long_benefits = [
                                            salesitem_client.models.item_benefit.itemBenefit(
                                                header = 'A safe lock', 
                                                name = 'PATRULL drawer/cabinet catch', 
                                                subject = 'Function/solution', 
                                                text = 'When your child feels like exploring the contents of cabinets and drawers PATRULL drawer/cabinet catch puts a stop to all attempts. But its easy for grown-ups to open - all you do is press lightly on the catch.', )
                                            ], 
                                        manufacturer = 'IKEA', 
                                        materials = [
                                            salesitem_client.models.item_customer_material.itemCustomerMaterial(
                                                part_materials = [
                                                    salesitem_client.models.item_part_material.itemPartMaterial(
                                                        material_text = '100% cotton', 
                                                        part_text = 'Total composition:', )
                                                    ], 
                                                product_type_text = 'Cover for 2-seat section', )
                                            ], 
                                        measurements = salesitem_client.models.item_measurements.itemMeasurements(
                                            detailed_measurements = [
                                                salesitem_client.models.detailed_measurement.detailedMeasurement(
                                                    text_imperial = '31 1/2 "', 
                                                    text_metric = '80 cm', 
                                                    type = 'HEIGHT_INCLUDING_BACK_CHUSHIONS', 
                                                    type_name = 'Height including back cushions', )
                                                ], 
                                            reference_measurements = [
                                                salesitem_client.models.reference_measurement.referenceMeasurement(
                                                    imperial = '7/3 cu.ft', 
                                                    metric = '210/79 l', )
                                                ], ), 
                                        media = [
                                            salesitem_client.models.item_media.itemMedia(
                                                action = salesitem_client.models.video_action.videoAction(
                                                    file_mime_type = 'image/jpeg', 
                                                    file_name = 'fe000181_890x500_00h_00m_01s.jpg', 
                                                    height = 500, 
                                                    href = 'https://mmapi.ikea.com/im/productfilms/images/fe000181_890x500_00h_00m_01s.jpg', 
                                                    width = 890, ), 
                                                alt_text = 'LANDSKRONA sofa with chaise long', 
                                                transcript = 'You don’t have to choose between a functional interior or clean exterior. This drawer front lets you have several smaller drawers behind a larger front or door – for both smart storage and a uniform look.', 
                                                id = '0602358', 
                                                information_dots = [
                                                    salesitem_client.models.media_information_dot.mediaInformationDot(
                                                        coordinates = salesitem_client.models.media_information_dot_coordinates.mediaInformationDotCoordinates(
                                                            x = 52.7, 
                                                            y = 34, ), 
                                                        header = 'Standard foam', 
                                                        icon = 'mattress-foam', 
                                                        text = 'Gives you all-over support and comfort.', )
                                                    ], 
                                                name = 'LANDSKRONA so3 w chs lng/Grann/Bomstad gld-br/wood MPP', 
                                                pe_no = 'PE680291', 
                                                poster = [
                                                    salesitem_client.models.video_poster.videoPoster(
                                                        file_mime_type = 'image/jpeg', 
                                                        file_name = 'fe000181_1920x1080_00h_00m_01s.jpg', 
                                                        height = 1080, 
                                                        href = 'https://mmapi.ikea.com/im/productfilms/images/fe000181_1920x1080_00h_00m_01s.jpg', 
                                                        quality = 'S5', 
                                                        width = 1920, )
                                                    ], 
                                                snapshots = [
                                                    salesitem_client.models.video_snapshot.videoSnapshot(
                                                        file_mime_type = 'image/jpeg', 
                                                        file_name = 'fe000181_114x64_00h_00m_00s.jpg', 
                                                        frame = 0, 
                                                        height = 114, 
                                                        href = 'https://mmapi.ikea.com/im/productfilms/images/fe000181_114x64_00h_00m_00s.jpg', 
                                                        width = 64, )
                                                    ], 
                                                thumbnail = salesitem_client.models.video_thumbnail.videoThumbnail(
                                                    file_mime_type = 'image/jpeg', 
                                                    file_name = 'fe000181_890x500_00h_00m_01s.jpg?imPolicy=thumbnail', 
                                                    height = 250, 
                                                    href = 'https://mmapi.ikea.com/im/productfilms/images/fe000181_890x500_00h_00m_01s.jpg?imPolicy=thumbnail', 
                                                    width = 250, ), 
                                                type_name = 'MAIN_PRODUCT_IMAGE', 
                                                type_no = '00001', )
                                            ], 
                                        package_measurements = [
                                            salesitem_client.models.item_package_measure.itemPackageMeasure(
                                                pack_no = 1, 
                                                text_imperial = '3 "', 
                                                text_metric = '8 cm', 
                                                type = 'LENGTH', 
                                                type_name = 'Length', 
                                                unit_imperial = '"', 
                                                unit_metric = 'cm', 
                                                value_imperial = '3', 
                                                value_metric = '8', )
                                            ], 
                                        product_name = 'VIMLE', 
                                        product_tags = [
                                            salesitem_client.models.locale_product_tag.localeProductTag(
                                                name = 'SLEEP_ON_IT_DAYS', )
                                            ], 
                                        product_type = salesitem_client.models.product_type.productType(
                                            id = '10210', 
                                            name = '2-seat sofa', ), 
                                        seo_slug = 'vimle-2-seat-sofa', 
                                        technical_compliance = [
                                            salesitem_client.models.technical_compliance.technicalCompliance(
                                                heading = 'Kostnadsspann alla modeller', 
                                                heading_global = 'Cost ranges All models', 
                                                heading_type = 'WATER_CONSUMPTION', 
                                                value = '2 - 3', )
                                            ], 
                                        technical_information = salesitem_client.models.technical_information.technicalInformation(
                                            information_groups = [
                                                salesitem_client.models.technical_information_group.technicalInformationGroup(
                                                    heading_no = '00033', 
                                                    heading_text = 'General', 
                                                    information_parts = [
                                                        salesitem_client.models.technical_information_part.technicalInformationPart(
                                                            explanatory_text = '', 
                                                            legal = True, 
                                                            range_no = '00004', 
                                                            range_text = 'Fridges/Freezers', 
                                                            text = 'Energy efficiency class', 
                                                            text_imperial = '', 
                                                            text_metric = 'A++', 
                                                            text_no = '00033', 
                                                            unit_imperial = '', 
                                                            unit_metric = '', 
                                                            value_imperial = '', 
                                                            value_metric = 'A++', )
                                                        ], )
                                                ], ), 
                                        valid_design = salesitem_client.models.valid_design.validDesign(
                                            text = 'Tallmyra black/gray', ), 
                                        warnings = [
                                            salesitem_client.models.warning.warning(
                                                type = 'CHOKING_HAZARD', )
                                            ], 
                                        benefits_as_is = [
                                            'Keeps the contents warm for longer and the outside cool, thanks to the double-walled glass.'
                                            ], 
                                        benefit_summary_as_is = 'Like a dream – a silky-soft duvet cover with a beautiful  luster. Sateen-woven from the finest yarn made of lyocell  and sustainably grown cotton. Natural materials that feel  good against your skin.
', )
                                    ], 
                                news = salesitem_client.models.news.news(
                                    valid_from = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                    valid_to = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                    value = True, ), 
                                number_of_packages = 3, 
                                product_name_global = 'VIMLE', 
                                product_tags = [
                                    salesitem_client.models.product_tag.productTag(
                                        name = 'NEW', 
                                        valid_from = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                        valid_to = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                                    ], 
                                product_type_classes = [
                                    'sofas'
                                    ], 
                                quantity = 1, 
                                style_group = 'IKEA Multi', 
                                unit_code = 'METER', )
                            ], 
                        class_unit_key = salesitem_client.models.class_unit_key.classUnitKey(
                            class_unit_code = '445', 
                            class_unit_type = 'STO', ), 
                        complementary_items = [
                            salesitem_client.models.complementary_item.complementaryItem(
                                type = 'MUST_BE_COMPLETED_WITH', )
                            ], 
                        filter_classes = [
                            'rugs'
                            ], 
                        generic_product = salesitem_client.models.generic_product.genericProduct(
                            gpr_no = '03067', ), 
                        is_assembly_required = True, 
                        is_breath_taking_item = True, 
                        is_new = True, 
                        item_key = , 
                        item_key_global = , 
                        kitchen_unit = salesitem_client.models.kitchen_unit.kitchenUnit(
                            value = True, ), 
                        last_chance = salesitem_client.models.last_chance.lastChance(
                            value = True, ), 
                        localised_communications = [
                            salesitem_client.models.localised.localised(
                                benefit_summary = 'Like a dream – a silky-soft duvet cover with a beautiful  luster. Sateen-woven from the finest yarn made of lyocell  and sustainably grown cotton. Natural materials that feel  good against your skin.
', 
                                item_name_local = 'BEKANT desk 160x80 white stained oak veneer/white', 
                                benefit_summary_as_is = 'Like a dream – a silky-soft duvet cover with a beautiful  luster. Sateen-woven from the finest yarn made of lyocell  and sustainably grown cotton. Natural materials that feel  good against your skin.
', )
                            ], 
                        news = salesitem_client.models.news.news(
                            valid_from = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            valid_to = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            value = True, ), 
                        number_of_packages = 3, 
                        presentation_group_code = 'ME/FÖ 140', 
                        price_quality_classification = 'HIGH', 
                        product_name_global = 'VIMLE', 
                        product_tags = [
                            salesitem_client.models.product_tag.productTag(
                                name = 'NEW', 
                                valid_from = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                valid_to = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                            ], 
                        product_type_classes = [
                            'sofas'
                            ], 
                        product_view_template = salesitem_client.models.product_view_template.productViewTemplate(
                            type = 'TECHNICAL', 
                            value = 'LOW', ), 
                        professional_assembly_time = salesitem_client.models.professional_assembly_time.professionalAssemblyTime(
                            unit = 'MINUTES', 
                            value = 120, ), 
                        service_product_relations = [
                            salesitem_client.models.service_product_relation.serviceProductRelation(
                                hide_service_from_customer = True, 
                                is_co_worker_assistance_needed = True, 
                                is_promoted = True, 
                                recommendation_rank = 1, 
                                relation_type = 'SOLD_WITH', 
                                service_key = , 
                                service_product_id = 'BASIC_KITCHEN_INSTALL', 
                                service_product_type = 'ASSEMBLY', )
                            ], 
                        style_group = 'IKEA Multi', 
                        unit_code = 'METER', 
                        experimental = [
                            salesitem_client.models.experimental_item.experimentalItem(
                                name = '', 
                                data = '', )
                            ], 
                        update_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testCommunicationResponse(self):
        """Test CommunicationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
