# coding: utf-8

"""
    Sales Item API

    Get information for items in different contexts. Note that this is an extendable interface that might introduce new types without increase in major version including new values in enumerations. 

    The version of the OpenAPI document: 1.45.0
    Contact: paul.eriksson@ingka.ikea.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from salesitem_client.models.assembly_effort import AssemblyEffort

class TestAssemblyEffort(unittest.TestCase):
    """AssemblyEffort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssemblyEffort:
        """Test AssemblyEffort
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssemblyEffort`
        """
        model = AssemblyEffort()
        if include_optional:
            return AssemblyEffort(
                estimated_time = salesitem_client.models.estimated_time.estimatedTime(
                    unit = 'MINUTES', 
                    value = 30, ),
                required_persons = 2,
                required_tools = [
                    salesitem_client.models.required_tool.requiredTool(
                        included_in_package = True, 
                        name = 'Allen Key', 
                        type = 'TOOL_ADJUSTABLE_PLIERS', )
                    ],
                type = 'CUSTOMER_ASSEMBLY'
            )
        else:
            return AssemblyEffort(
        )
        """

    def testAssemblyEffort(self):
        """Test AssemblyEffort"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
