# coding: utf-8

"""
    Sales Item API

    Get information for items in different contexts. Note that this is an extendable interface that might introduce new types without increase in major version including new values in enumerations. 

    The version of the OpenAPI document: 1.45.0
    Contact: paul.eriksson@ingka.ikea.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from salesitem_client.models.detailed_measurement import DetailedMeasurement

class TestDetailedMeasurement(unittest.TestCase):
    """DetailedMeasurement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DetailedMeasurement:
        """Test DetailedMeasurement
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DetailedMeasurement`
        """
        model = DetailedMeasurement()
        if include_optional:
            return DetailedMeasurement(
                text_imperial = '31 1/2 "',
                text_metric = '80 cm',
                type = 'HEIGHT_INCLUDING_BACK_CHUSHIONS',
                type_name = 'Height including back cushions'
            )
        else:
            return DetailedMeasurement(
        )
        """

    def testDetailedMeasurement(self):
        """Test DetailedMeasurement"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
