# coding: utf-8

"""
    Sales Item API

    Get information for items in different contexts. Note that this is an extendable interface that might introduce new types without increase in major version including new values in enumerations. 

    The version of the OpenAPI document: 1.45.0
    Contact: paul.eriksson@ingka.ikea.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from salesitem_client.models.availability_classification_response import AvailabilityClassificationResponse

class TestAvailabilityClassificationResponse(unittest.TestCase):
    """AvailabilityClassificationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AvailabilityClassificationResponse:
        """Test AvailabilityClassificationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AvailabilityClassificationResponse`
        """
        model = AvailabilityClassificationResponse()
        if include_optional:
            return AvailabilityClassificationResponse(
                data = [
                    salesitem_client.models.item_availability_classification.itemAvailabilityClassification(
                        availability_classifications = [
                            salesitem_client.models.availability_classification.availabilityClassification(
                                channel = 'ONLINE', 
                                type = 'CUSTOMER_PURCHASE', 
                                value = True, )
                            ], 
                        class_unit_key = salesitem_client.models.class_unit_key.classUnitKey(
                            class_unit_code = '445', 
                            class_unit_type = 'STO', ), 
                        item_key = salesitem_client.models.item_key.itemKey(
                            item_no = '00263850', 
                            item_type = 'ART', ), 
                        update_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                error = salesitem_client.models.status.status(
                    code = 56, 
                    details = [
                        {
                            'key' : None
                            }
                        ], 
                    message = '', ),
                trace_id = '8e893adf-c115-46bb-ab5d-378c177a096e'
            )
        else:
            return AvailabilityClassificationResponse(
        )
        """

    def testAvailabilityClassificationResponse(self):
        """Test AvailabilityClassificationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
