# coding: utf-8

"""
    Sales Item API

    Get information for items in different contexts. Note that this is an extendable interface that might introduce new types without increase in major version including new values in enumerations. 

    The version of the OpenAPI document: 1.45.0
    Contact: paul.eriksson@ingka.ikea.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from salesitem_client.models.compliance_information import ComplianceInformation

class TestComplianceInformation(unittest.TestCase):
    """ComplianceInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComplianceInformation:
        """Test ComplianceInformation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComplianceInformation`
        """
        model = ComplianceInformation()
        if include_optional:
            return ComplianceInformation(
                sections = [
                    salesitem_client.models.compliance_information_section.complianceInformationSection(
                        heading = 'Holzart', 
                        urls = [
                            salesitem_client.models.compliance_url.complianceUrl(
                                text = 'DTSCCalSAFER', 
                                url = 'https://calsafer.dtsc.ca.gov/cms/search/?type=Chemical', )
                            ], 
                        values = [
                            'Buche (Fagus sylvatica); Land des Holzeinschlags: Republik Kroatien, SLOWAKEI, SLOWENIEN'
                            ], )
                    ],
                type = 'CALIFORNIA_AB_1200'
            )
        else:
            return ComplianceInformation(
                sections = [
                    salesitem_client.models.compliance_information_section.complianceInformationSection(
                        heading = 'Holzart', 
                        urls = [
                            salesitem_client.models.compliance_url.complianceUrl(
                                text = 'DTSCCalSAFER', 
                                url = 'https://calsafer.dtsc.ca.gov/cms/search/?type=Chemical', )
                            ], 
                        values = [
                            'Buche (Fagus sylvatica); Land des Holzeinschlags: Republik Kroatien, SLOWAKEI, SLOWENIEN'
                            ], )
                    ],
                type = 'CALIFORNIA_AB_1200',
        )
        """

    def testComplianceInformation(self):
        """Test ComplianceInformation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
