# coding: utf-8

"""
    Sales Item API

    Get information for items in different contexts. Note that this is an extendable interface that might introduce new types without increase in major version including new values in enumerations. 

    The version of the OpenAPI document: 1.45.0
    Contact: paul.eriksson@ingka.ikea.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from salesitem_client.models.sales_price import SalesPrice

class TestSalesPrice(unittest.TestCase):
    """SalesPrice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SalesPrice:
        """Test SalesPrice
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SalesPrice`
        """
        model = SalesPrice()
        if include_optional:
            return SalesPrice(
                change_reason = 'NewLowerPrice',
                currency_code = '',
                indicative_discount = 1,
                indicative_total_tax = 1.337,
                lowest_previous_sales_price = salesitem_client.models.sales_price_previous_sales_price.salesPricePreviousSalesPrice(
                    display = True, 
                    indicative_total_tax = 0.81, 
                    price_excl_tax = 8.19, 
                    price_incl_tax = 9, 
                    unit_price = salesitem_client.models.sales_price_unit_price.salesPriceUnitPrice(
                        indicative_imperial_total_tax = 1.337, 
                        indicative_metric_total_tax = 1.337, 
                        price_imperial_excl_tax = 1.337, 
                        price_imperial_incl_tax = 1.337, 
                        price_metric_excl_tax = 1.337, 
                        price_metric_incl_tax = 1.337, 
                        unit_price_texts = [
                            salesitem_client.models.sales_price_unit_price_unit_price_texts.salesPriceUnitPrice_unitPriceTexts(
                                country_code = '', 
                                language_code = '', 
                                unit_text_imperial = '', 
                                unit_text_metric = '', )
                            ], 
                        display = True, ), ),
                previous_sales_price = salesitem_client.models.sales_price_previous_sales_price.salesPricePreviousSalesPrice(
                    display = True, 
                    indicative_total_tax = 0.81, 
                    price_excl_tax = 8.19, 
                    price_incl_tax = 9, 
                    unit_price = salesitem_client.models.sales_price_unit_price.salesPriceUnitPrice(
                        indicative_imperial_total_tax = 1.337, 
                        indicative_metric_total_tax = 1.337, 
                        price_imperial_excl_tax = 1.337, 
                        price_imperial_incl_tax = 1.337, 
                        price_metric_excl_tax = 1.337, 
                        price_metric_incl_tax = 1.337, 
                        unit_price_texts = [
                            salesitem_client.models.sales_price_unit_price_unit_price_texts.salesPriceUnitPrice_unitPriceTexts(
                                country_code = '', 
                                language_code = '', 
                                unit_text_imperial = '', 
                                unit_text_metric = '', )
                            ], 
                        display = True, ), ),
                price_excl_tax = 1.337,
                price_incl_tax = 1.337,
                type = 'RegularSalesUnitPrice',
                unit_price = salesitem_client.models.sales_price_unit_price.salesPriceUnitPrice(
                    indicative_imperial_total_tax = 1.337, 
                    indicative_metric_total_tax = 1.337, 
                    price_imperial_excl_tax = 1.337, 
                    price_imperial_incl_tax = 1.337, 
                    price_metric_excl_tax = 1.337, 
                    price_metric_incl_tax = 1.337, 
                    unit_price_texts = [
                        salesitem_client.models.sales_price_unit_price_unit_price_texts.salesPriceUnitPrice_unitPriceTexts(
                            country_code = '', 
                            language_code = '', 
                            unit_text_imperial = '', 
                            unit_text_metric = '', )
                        ], 
                    display = True, ),
                experimental_discount_amount = 1.337,
                experimental_discount_percentage = 1.337,
                valid_from_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                valid_to_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return SalesPrice(
        )
        """

    def testSalesPrice(self):
        """Test SalesPrice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
