# coding: utf-8

"""
    Sales Item API

    Get information for items in different contexts. Note that this is an extendable interface that might introduce new types without increase in major version including new values in enumerations. 

    The version of the OpenAPI document: 1.45.0
    Contact: paul.eriksson@ingka.ikea.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from salesitem_client.api.generic_product_api import GenericProductApi


class TestGenericProductApi(unittest.TestCase):
    """GenericProductApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GenericProductApi()

    def tearDown(self) -> None:
        pass

    def test_get_generic_product_communication(self) -> None:
        """Test case for get_generic_product_communication

        Get Generic Product communication.
        """
        pass


if __name__ == '__main__':
    unittest.main()
