# coding: utf-8

"""
    Open-Meteo Weather API

    REST API for retrieving current weather data from Open-Meteo.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weather_client.models.forecast_get200_response_current_weather_units import ForecastGet200ResponseCurrentWeatherUnits

class TestForecastGet200ResponseCurrentWeatherUnits(unittest.TestCase):
    """ForecastGet200ResponseCurrentWeatherUnits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ForecastGet200ResponseCurrentWeatherUnits:
        """Test ForecastGet200ResponseCurrentWeatherUnits
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ForecastGet200ResponseCurrentWeatherUnits`
        """
        model = ForecastGet200ResponseCurrentWeatherUnits()
        if include_optional:
            return ForecastGet200ResponseCurrentWeatherUnits(
                time = 'iso8601',
                interval = 'seconds',
                temperature = '°C',
                windspeed = 'km/h',
                winddirection = '°',
                is_day = '',
                weathercode = 'wmo code'
            )
        else:
            return ForecastGet200ResponseCurrentWeatherUnits(
        )
        """

    def testForecastGet200ResponseCurrentWeatherUnits(self):
        """Test ForecastGet200ResponseCurrentWeatherUnits"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
