# coding: utf-8

"""
    Open-Meteo Weather API

    REST API for retrieving current weather data from Open-Meteo.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weather_client.models.forecast_get200_response_current_weather import ForecastGet200ResponseCurrentWeather

class TestForecastGet200ResponseCurrentWeather(unittest.TestCase):
    """ForecastGet200ResponseCurrentWeather unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ForecastGet200ResponseCurrentWeather:
        """Test ForecastGet200ResponseCurrentWeather
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ForecastGet200ResponseCurrentWeather`
        """
        model = ForecastGet200ResponseCurrentWeather()
        if include_optional:
            return ForecastGet200ResponseCurrentWeather(
                time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                interval = 900,
                temperature = 22.8,
                windspeed = 8.9,
                winddirection = 40,
                is_day = 0,
                weathercode = 0
            )
        else:
            return ForecastGet200ResponseCurrentWeather(
        )
        """

    def testForecastGet200ResponseCurrentWeather(self):
        """Test ForecastGet200ResponseCurrentWeather"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
